// catalog_v1.py를 TypeScript로 포팅.
// 카탈로그 SKU 19개 + generated mining catalog + normalize + ruleMatch.

import { GENERATED_CATALOG } from "@/lib/generated/catalog";

export type Sku = {
  id: string;
  brand: string;
  category: "earphone" | "smartwatch" | "smartphone" | "tablet" | "laptop" | "monitor" | "speaker" | "camera" | "game_console" | "small_appliance";
  modelName: string;
  aliases: string[];
  mustContain: string[][];
  mustNotContain: string[];
  msrpKrw: number;
  released: number;
  // Optional narrow-lane tag. When set, this SKU belongs to a specific runtime
  // lane (e.g. "ps5_disc_digital_standard") whose readiness in
  // `LANE_READINESS` overrides the broader category gate.
  laneKey?: string;
};

const PHONE_NOISE = [
  "케이스",
  "case",
  "폰케이스",
  "그립톡",
  "스마트톡",
  "맥세이프",
  "파인우븐",
  "슬림아머",
  "슈피겐",
  "어반소피스티케이션",
  "모란카노",
  "tyreus",
  "디월렛",
  "다이어리",
  "필름",
  "강화유리",
  "키보드",
  "키패드",
  "물리키패드",
  "충전기만",
  "어댑터만",
  "액정",
  "액정만",
  "배터리만",
  "메인보드",
  "뒷판",
  "후면유리",
  "후면 유리",
  "후면판",
  "백글라스",
  "하우징",
  "카메라렌즈",
  "카메라 렌즈",
  "충전단자",
  "줄이어폰",
  "부품용",
  "파손폰",
  "고장폰",
  "고장",
  "분실폰",
  "잠김",
  "락걸림",
  "매입",
  "삽니다",
  "구합니다",
  "구해봅니다",
  "구매함",
  "최고가",
  "대여",
  "렌탈",
  "색상교환",
  "교환하실분",
  "교환하실 분",
];

const TABLET_NOISE = [
  "케이스",
  "필름",
  "강화유리",
  "펜슬만",
  "애플펜슬만",
  "키보드만",
  "매직키보드만",
  "충전기만",
  "액정",
  "액정만",
  "배터리만",
  "부품용",
  "파손",
  "고장",
  "매입",
  "삽니다",
  "구합니다",
  "대여",
  "렌탈",
];

const HEADPHONE_NOISE = [
  "이어패드만",
  "이어 패드만",
  "이어쿠션만",
  "이어 쿠션만",
  "헤드쿠션만",
  "헤드 쿠션만",
  "케이스만",
  "파우치만",
  "거치대만",
  "스탠드만",
  "충전기만",
  "케이블만",
  "부품용",
  "고장",
  "불량",
  "삽니다",
  "구합니다",
  "매입",
];

const SPEAKER_NOISE = [
  "케이스",
  "case",
  "하드쉘",
  "파우치",
  "가방",
  "커버",
  "스탠드만",
  "거치대만",
  "충전기만",
  "케이블만",
  "마이크",
  "무선마이크",
  "노래방",
  "karaoke",
  "pa",
  "리시버",
  "receiver",
  "앰프",
  "amp",
  "사운드바",
  "soundbar",
  "일괄",
  "고장",
  "파손",
  "대여",
  "렌탈",
  "삽니다",
  "구합니다",
  "매입",
];

const CAMERA_BODY_ONLY_NOISE = [
  "렌즈",
  "lens",
  "번들",
  "번들킷",
  "키트",
  "kit",
  "세트",
  "풀셋",
  "풀셋트",
  "바디캡",
  "렌즈캡",
  "뒷캡",
  "캡",
  "케이스",
  "가방",
  "하자",
  "수리필요",
  "부품용",
  "고장",
  "구매",
  "삽니다",
  "구합니다",
  "업자x",
  "사기꾼",
  "바디프렌드",
];

const LAPTOP_NOISE = [
  "메인보드",
  "메인 보드",
  "로직보드",
  "로직 보드",
  "상판",
  "하판",
  "액정만",
  "배터리만",
  "키보드만",
  "부품용",
  "부품",
  "고장",
  "침수",
];

const GENERATED_CATALOG_WITH_GATES: Sku[] = GENERATED_CATALOG.map((sku) => {
  if (sku.category !== "laptop") return sku;
  return {
    ...sku,
    mustNotContain: [...new Set([...sku.mustNotContain, ...LAPTOP_NOISE])],
  };
});

const CORE_SMARTPHONE_CATALOG: Sku[] = [
  {
    id: "iphone-13-pro",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 13 Pro",
    aliases: ["아이폰 13 프로", "아이폰13프로", "iPhone 13 Pro"],
    mustContain: [["아이폰 13 프로", "아이폰13프로", "iphone 13 pro"]],
    mustNotContain: ["프로맥스", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1350000,
    released: 2021,
  },
  {
    id: "iphone-13-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 13 Pro Max",
    aliases: ["아이폰 13 프로맥스", "아이폰13프로맥스", "iPhone 13 Pro Max"],
    mustContain: [["아이폰 13 프로맥스", "아이폰13프로맥스", "iphone 13 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1490000,
    released: 2021,
  },
  {
    id: "iphone-14-pro",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 14 Pro",
    aliases: ["아이폰 14 프로", "아이폰14프로", "iPhone 14 Pro"],
    mustContain: [["아이폰 14 프로", "아이폰14프로", "iphone 14 pro"]],
    mustNotContain: ["프로맥스", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1550000,
    released: 2022,
  },
  {
    id: "iphone-14-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 14 Pro Max",
    aliases: ["아이폰 14 프로맥스", "아이폰14프로맥스", "iPhone 14 Pro Max"],
    mustContain: [["아이폰 14 프로맥스", "아이폰14프로맥스", "iphone 14 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1750000,
    released: 2022,
  },
  {
    id: "iphone-15-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 15 Pro Max",
    aliases: ["아이폰 15 프로맥스", "아이폰15프로맥스", "iPhone 15 Pro Max"],
    mustContain: [["아이폰 15 프로맥스", "아이폰15프로맥스", "iphone 15 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1900000,
    released: 2023,
  },
  {
    id: "iphone-15-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_15_pro_128gb_self",
    modelName: "iPhone 15 Pro 128GB (자급제)",
    aliases: ["아이폰 15 프로 128 자급제", "iPhone 15 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 15 프로", "아이폰15프로", "iphone 15 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 14", "iphone 14", "아이폰14",
      "아이폰 16", "iphone 16", "아이폰16",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1550000,
    released: 2023,
  },
  {
    id: "iphone-16e",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 16e",
    aliases: ["아이폰 16e", "아이폰16e", "iPhone 16e"],
    mustContain: [["아이폰 16e", "아이폰16e", "iphone 16e"]],
    mustNotContain: ["프로", "pro", "프로맥스", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 990000,
    released: 2025,
  },
  {
    id: "iphone-16-pro",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 16 Pro",
    aliases: ["아이폰 16 프로", "아이폰16프로", "iPhone 16 Pro"],
    mustContain: [["아이폰 16 프로", "아이폰16프로", "iphone 16 pro"]],
    mustNotContain: ["프로맥스", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1550000,
    released: 2024,
  },
  {
    id: "iphone-16-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_16_pro_128gb_self",
    modelName: "iPhone 16 Pro 128GB (자급제)",
    aliases: ["아이폰 16 프로 128 자급제", "iPhone 16 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 16 프로", "아이폰16프로", "iphone 16 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 15", "iphone 15", "아이폰15",
      "아이폰 17", "iphone 17", "아이폰17",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1550000,
    released: 2024,
  },
  {
    id: "iphone-16-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 16 Pro Max",
    aliases: ["아이폰 16 프로맥스", "아이폰16프로맥스", "iPhone 16 Pro Max"],
    mustContain: [["아이폰 16 프로맥스", "아이폰16프로맥스", "iphone 16 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1900000,
    released: 2024,
  },
  {
    id: "galaxy-s23-ultra",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S23 Ultra",
    aliases: ["갤럭시 S23 울트라", "갤럭시S23울트라", "Galaxy S23 Ultra"],
    mustContain: [["갤럭시 s23 울트라", "갤럭시s23울트라", "galaxy s23 ultra", "s23 ultra"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1600000,
    released: 2023,
  },
  {
    id: "galaxy-s24-ultra",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S24 Ultra",
    aliases: ["갤럭시 S24 울트라", "갤럭시S24울트라", "Galaxy S24 Ultra"],
    mustContain: [["갤럭시 s24 울트라", "갤럭시s24울트라", "galaxy s24 ultra", "s24 ultra"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1700000,
    released: 2024,
  },
  {
    id: "galaxy-s25",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S25",
    aliases: ["갤럭시 S25", "갤럭시S25", "Galaxy S25"],
    mustContain: [["갤럭시 s25", "갤럭시s25", "galaxy s25", "s25"]],
    mustNotContain: ["울트라", "ultra", "플러스", "plus", "gs25", ...PHONE_NOISE],
    msrpKrw: 1150000,
    released: 2025,
  },
  {
    id: "galaxy-s25-plus",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S25 Plus",
    aliases: ["갤럭시 S25 플러스", "갤럭시S25플러스", "Galaxy S25 Plus"],
    mustContain: [["갤럭시 s25 플러스", "갤럭시s25플러스", "galaxy s25 plus", "s25 plus"]],
    mustNotContain: ["울트라", "ultra", ...PHONE_NOISE],
    msrpKrw: 1350000,
    released: 2025,
  },
  {
    id: "galaxy-s25-ultra",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S25 Ultra",
    aliases: ["갤럭시 S25 울트라", "갤럭시S25울트라", "Galaxy S25 Ultra"],
    mustContain: [["갤럭시 s25 울트라", "갤럭시s25울트라", "galaxy s25 ultra", "s25 ultra"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1700000,
    released: 2025,
  },
  {
    id: "galaxy-s25-ultra-256-self",
    brand: "Samsung",
    category: "smartphone",
    laneKey: "galaxy_s25_ultra_256_self",
    modelName: "Galaxy S25 Ultra 256GB (자급제)",
    aliases: ["갤럭시 S25 울트라 256 자급제", "Galaxy S25 Ultra 256 SIM-Free"],
    mustContain: [
      ["갤럭시 s25 울트라", "갤럭시s25울트라", "galaxy s25 ultra", "s25 ultra"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "s24", "갤럭시 s24", "galaxy s24",
      "s23", "갤럭시 s23", "galaxy s23",
      "s26", "갤럭시 s26", "galaxy s26",
      "플러스", "plus", "일반", "basic",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1700000,
    released: 2025,
  },
];

const CORE_TABLET_CATALOG: Sku[] = [
  {
    id: "ipad-pro",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad Pro",
    aliases: ["아이패드 프로", "아이패드프로", "iPad Pro"],
    mustContain: [["아이패드", "ipad"], ["프로", "pro"]],
    mustNotContain: ["에어", "air", "미니", "mini", "a17pro", "a17 pro", ...TABLET_NOISE],
    msrpKrw: 1500000,
    released: 2024,
  },
  {
    id: "ipad-pro-11-m4-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_pro_11_m4_256_wifi",
    modelName: "iPad Pro 11\" M4 256GB Wi-Fi",
    aliases: ["아이패드 프로 11 M4 256", "iPad Pro 11 M4 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["프로", "pro"],
      ["m4"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["11인치", "11 인치", "11형", "11\"", "11″"],
    ],
    mustNotContain: [
      "에어", "air", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"", "12.9인치", "12.9 인치", "12.9\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "2tb", "2 tb", "2테라",
      "(m1)", "(m2)", "(m3)", " m1 ", " m2 ", " m3 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1899000,
    released: 2024,
  },
  {
    id: "ipad-pro-13-m4-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_pro_13_m4_256_wifi",
    modelName: "iPad Pro 13\" M4 256GB Wi-Fi",
    aliases: ["아이패드 프로 13 M4 256", "iPad Pro 13 M4 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["프로", "pro"],
      ["m4"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["13인치", "13 인치", "13형", "13\"", "13″"],
    ],
    mustNotContain: [
      "에어", "air", "미니", "mini",
      "11인치", "11 인치", "11형", "11\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb",
      "1tb", "2tb",
      "(m1)", "(m2)", "(m3)", " m1 ", " m2 ", " m3 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 2399000,
    released: 2024,
  },
  {
    id: "ipad-air",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad Air",
    aliases: ["아이패드 에어", "아이패드에어", "iPad Air"],
    mustContain: [["아이패드", "ipad"], ["에어", "air"]],
    mustNotContain: ["프로", "pro", "미니", "mini", ...TABLET_NOISE],
    msrpKrw: 900000,
    released: 2024,
  },
  {
    id: "ipad-air-m2-11-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_air_m2_11_256_wifi",
    modelName: "iPad Air M2 11\" 256GB Wi-Fi",
    aliases: ["아이패드 에어 11 M2 256", "iPad Air 11 M2 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["에어", "air"],
      ["m2"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["11인치", "11 인치", "11형", "11\"", "11″"],
    ],
    mustNotContain: [
      "프로", "pro", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"", "12.9인치", "12.9 인치", "12.9\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "2tb", "2 tb", "2테라",
      "(m1)", "(m3)", " m1 ", " m3 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 999000,
    released: 2024,
  },
  {
    id: "ipad-air-m3-11-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_air_m3_11_256_wifi",
    modelName: "iPad Air M3 11\" 256GB Wi-Fi",
    aliases: ["아이패드 에어 11 M3 256", "iPad Air 11 M3 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["에어", "air"],
      ["m3"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["11인치", "11 인치", "11형", "11\""],
    ],
    mustNotContain: [
      "프로", "pro", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"",
      "셀룰러", "cellular", "유심", "esim",
      "128gb", "128 gb",
      "512gb", "1tb", "2tb",
      "(m1)", "(m2)", "(m4)", " m1 ", " m2 ", " m4 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1099000,
    released: 2025,
  },
  {
    id: "ipad-mini",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad mini",
    aliases: ["아이패드 미니", "아이패드미니", "iPad mini"],
    mustContain: [["아이패드", "ipad"], ["미니", "mini"]],
    mustNotContain: ["프로", "pro", "에어", "air", ...TABLET_NOISE],
    msrpKrw: 750000,
    released: 2024,
  },
  {
    id: "ipad-10",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad 10th gen",
    aliases: ["아이패드 10세대", "아이패드10세대", "iPad 10th gen"],
    mustContain: [["아이패드", "ipad"], ["10세대", "10 세대", "10th", "ipad 10"]],
    mustNotContain: ["프로", "pro", "에어", "air", "미니", "mini", ...TABLET_NOISE],
    msrpKrw: 680000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s8",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S8",
    aliases: ["갤럭시탭 S8", "갤탭 S8", "Galaxy Tab S8"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s8", "s 8"]],
    mustNotContain: ["s8 울트라", "s8 ultra", "s8 플러스", "s8 plus", ...TABLET_NOISE],
    msrpKrw: 900000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s8-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S8 Plus",
    aliases: ["갤럭시탭 S8 플러스", "갤탭 S8+", "Galaxy Tab S8 Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s8", "s 8"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 1100000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s8-ultra",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S8 Ultra",
    aliases: ["갤럭시탭 S8 울트라", "갤탭 S8 울트라", "Galaxy Tab S8 Ultra"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s8", "s 8"], ["울트라", "ultra"]],
    mustNotContain: ["플러스", "plus", ...TABLET_NOISE],
    msrpKrw: 1400000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s9",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9",
    aliases: ["갤럭시탭 S9", "갤탭 S9", "Galaxy Tab S9"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"]],
    mustNotContain: ["s9 울트라", "s9 ultra", "s9 플러스", "s9 plus", "fe", "팬에디션", ...TABLET_NOISE],
    msrpKrw: 1000000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-fe",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 FE",
    aliases: ["갤럭시탭 S9 FE", "갤탭 S9 FE", "Galaxy Tab S9 FE"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["fe", "팬에디션"]],
    mustNotContain: ["플러스", "plus", "울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 629000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-fe-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 FE Plus",
    aliases: ["갤럭시탭 S9 FE 플러스", "갤탭 S9 FE+", "Galaxy Tab S9 FE Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["fe", "팬에디션"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 799000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 Plus",
    aliases: ["갤럭시탭 S9 플러스", "갤탭 S9+", "Galaxy Tab S9 Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", "fe", "팬에디션", ...TABLET_NOISE],
    msrpKrw: 1200000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-ultra",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 Ultra",
    aliases: ["갤럭시탭 S9 울트라", "갤탭 S9 울트라", "Galaxy Tab S9 Ultra"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["울트라", "ultra"]],
    mustNotContain: ["플러스", "plus", ...TABLET_NOISE],
    msrpKrw: 1600000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s10-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S10 Plus",
    aliases: ["갤럭시탭 S10 플러스", "갤탭 S10+", "Galaxy Tab S10 Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s10", "s 10"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", "fe", "팬에디션", ...TABLET_NOISE],
    msrpKrw: 1250000,
    released: 2024,
  },
  {
    id: "galaxy-tab-s10-fe-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S10 FE Plus",
    aliases: ["갤럭시탭 S10 FE 플러스", "갤탭 S10 FE+", "Galaxy Tab S10 FE Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s10", "s 10"], ["fe", "팬에디션"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 899000,
    released: 2025,
  },
  {
    id: "galaxy-tab-s10-ultra",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S10 Ultra",
    aliases: ["갤럭시탭 S10 울트라", "갤탭 S10 울트라", "Galaxy Tab S10 Ultra"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s10", "s 10"], ["울트라", "ultra"]],
    mustNotContain: ["플러스", "plus", ...TABLET_NOISE],
    msrpKrw: 1700000,
    released: 2024,
  },
];

const CORE_LAPTOP_CATALOG: Sku[] = [
  {
    id: "macbook-air-m3-13-256",
    brand: "Apple",
    category: "laptop",
    laneKey: "macbook_air_m3_13_256",
    modelName: "MacBook Air M3 13\" 256GB",
    aliases: ["맥북 에어 M3 13 256", "MacBook Air M3 13\" 256GB"],
    mustContain: [
      ["맥북", "macbook"],
      ["에어", "air"],
      ["m3"],
      ["13인치", "13 인치", "13형", "13\""],
    ],
    mustNotContain: [
      "프로", "pro",
      "15인치", "15형",
      "(m1)", "(m2)", "(m4)",
      " m1 ", " m2 ", " m4 ",
      "메인보드", "로직보드", "상판", "하판",
      "액정만", "배터리만", "키보드만",
      "부품", "고장", "침수",
      "매입", "삽니다",
    ],
    msrpKrw: 1390000,
    released: 2024,
  },
];

export const CATALOG: Sku[] = [
  // ─── Monitor exact model-code review candidates ─────
  {
    id: "monitor-xl2540k",
    brand: "BenQ ZOWIE",
    category: "monitor",
    laneKey: "monitor_benq_xl2540k",
    modelName: "BenQ ZOWIE XL2540K",
    aliases: ["XL2540K", "벤큐 XL2540K", "ZOWIE XL2540K"],
    mustContain: [["xl2540k"]],
    mustNotContain: [],
    msrpKrw: 499000,
    released: 2020,
  },
  {
    id: "monitor-27us550",
    brand: "LG",
    category: "monitor",
    modelName: "LG 27US550",
    aliases: ["27US550", "LG 27US550", "27US550-W"],
    mustContain: [["27us550"]],
    mustNotContain: [],
    msrpKrw: 399000,
    released: 2024,
  },
  {
    id: "monitor-ls27f354fhk",
    brand: "Samsung",
    category: "monitor",
    modelName: "Samsung LS27F354FHK",
    aliases: ["LS27F354FHK", "삼성 LS27F354FHK"],
    mustContain: [["ls27f354fhk"]],
    mustNotContain: [],
    msrpKrw: 249000,
    released: 2016,
  },
  {
    id: "monitor-39gx900a",
    brand: "LG",
    category: "monitor",
    modelName: "LG 39GX900A",
    aliases: ["39GX900A", "39GX900A-B", "LG 39GX900A"],
    mustContain: [["39gx900a"]],
    mustNotContain: [],
    msrpKrw: 2190000,
    released: 2025,
  },
  {
    id: "monitor-aw2525hm",
    brand: "Dell Alienware",
    category: "monitor",
    modelName: "Dell Alienware AW2525HM",
    aliases: ["AW2525HM", "Alienware AW2525HM"],
    mustContain: [["aw2525hm"]],
    mustNotContain: [],
    msrpKrw: 499000,
    released: 2025,
  },
  {
    id: "monitor-27gl650f",
    brand: "LG",
    category: "monitor",
    modelName: "LG UltraGear 27GL650F",
    aliases: ["27GL650F", "LG 27GL650F", "울트라기어 27GL650F"],
    mustContain: [["27gl650f"]],
    mustNotContain: [],
    msrpKrw: 399000,
    released: 2019,
  },
  // ─── Portable Bluetooth speaker exact-model review candidates ───
  {
    id: "speaker-jbl-go-3",
    brand: "JBL",
    category: "speaker",
    modelName: "JBL GO 3",
    aliases: ["JBL GO 3", "JBL GO3", "제이비엘 GO3"],
    mustContain: [["jbl", "제이비엘"], ["go3", "go 3"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 49900,
    released: 2020,
  },
  {
    id: "speaker-jbl-go-4",
    brand: "JBL",
    category: "speaker",
    modelName: "JBL GO 4",
    aliases: ["JBL GO 4", "JBL GO4", "제이비엘 GO4"],
    mustContain: [["jbl", "제이비엘"], ["go4", "go 4"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 59900,
    released: 2024,
  },
  {
    id: "speaker-jbl-flip-6",
    brand: "JBL",
    category: "speaker",
    laneKey: "speaker_jbl_flip6",
    modelName: "JBL Flip 6",
    aliases: ["JBL Flip 6", "JBL Flip6", "JBL 플립6", "제이비엘 플립6"],
    mustContain: [["jbl", "제이비엘"], ["flip6", "flip 6", "플립6"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 149000,
    released: 2021,
  },
  {
    id: "speaker-jbl-boombox-2",
    brand: "JBL",
    category: "speaker",
    modelName: "JBL Boombox 2",
    aliases: ["JBL Boombox 2", "JBL 붐박스2", "JBL 붐박스 2"],
    mustContain: [["jbl", "제이비엘"], ["boombox 2", "boombox2", "붐박스2", "붐박스 2"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 599000,
    released: 2020,
  },
  {
    id: "speaker-lg-pk5",
    brand: "LG",
    category: "speaker",
    modelName: "LG PK5",
    aliases: ["LG PK5", "엘지 PK5"],
    mustContain: [["lg", "엘지"], ["pk5", "pk 5"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 199000,
    released: 2018,
  },
  {
    id: "speaker-lg-pk7w",
    brand: "LG",
    category: "speaker",
    modelName: "LG PK7W",
    aliases: ["LG PK7W", "엘지 PK7W", "LG 엑스붐 PK7W"],
    mustContain: [["lg", "엘지"], ["pk7w", "pk 7w"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 299000,
    released: 2018,
  },
  // ─── Camera body-only exact-model internal candidates ───
  {
    id: "camera-canon-eos-r6-mark-ii",
    brand: "Canon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Canon EOS R6 Mark II",
    aliases: ["Canon EOS R6 Mark II", "캐논 EOS R6 Mark II", "알육막투", "R6M2"],
    mustContain: [["eos r6 mark ii", "r6 mark ii", "r6m2", "알육막투"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 3199000,
    released: 2022,
  },
  {
    id: "camera-sony-a7m3",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A7 III",
    aliases: ["Sony A7 III", "Sony A7M3", "소니 A7M3", "ILCE-7M3"],
    mustContain: [["a7m3", "a7 iii", "a7 3", "ilce 7m3"], ["바디", "바디만", "바디셋", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a7m2", "a7m4", "a7r3", "a7r iii", "a7s3", "a7s iii"],
    msrpKrw: 2499000,
    released: 2018,
  },
  {
    id: "camera-sony-a7c",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A7C",
    aliases: ["Sony A7C", "소니 A7C", "ILCE-7C"],
    mustContain: [["a7c", "ilce 7c"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a7c2", "7cm2", "ilce 7cm2"],
    msrpKrw: 2199000,
    released: 2020,
  },
  {
    id: "camera-sony-a5100",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A5100",
    aliases: ["Sony A5100", "소니 A5100", "ILCE-5100"],
    mustContain: [["a5100", "ilce 5100"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 698000,
    released: 2014,
  },
  {
    id: "camera-canon-eos-m6",
    brand: "Canon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Canon EOS M6",
    aliases: ["Canon EOS M6", "캐논 EOS M6"],
    mustContain: [["eos m6", "캐논 m6"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 899000,
    released: 2017,
  },
  {
    id: "camera-nikon-z9",
    brand: "Nikon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Nikon Z9",
    aliases: ["Nikon Z9", "니콘 Z9"],
    mustContain: [["z9", "니콘 z9"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 6998000,
    released: 2021,
  },
  {
    id: "camera-canon-eos-6d",
    brand: "Canon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Canon EOS 6D",
    aliases: ["Canon EOS 6D", "캐논 EOS 6D"],
    mustContain: [["eos 6d", "캐논 6d"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 2490000,
    released: 2012,
  },
  {
    id: "camera-fujifilm-x-t4",
    brand: "Fujifilm",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Fujifilm X-T4",
    aliases: ["Fujifilm X-T4", "후지필름 X-T4", "후지 X-T4"],
    mustContain: [["x-t4", "x t4", "xt4"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 2099000,
    released: 2020,
  },
  // ─── PlayStation 5 (Standard, Disc/Digital) ─────────
  // narrow lane: ps5_disc_digital_standard (Slim/Pro/PSVR/Switch/액세서리 차단)
  {
    id: "ps5-disc-standard",
    brand: "Sony",
    category: "game_console",
    laneKey: "ps5_disc_digital_standard",
    modelName: "PlayStation 5 (Disc, Standard)",
    aliases: ["PS5 디스크", "PS5 Disc", "플스5 디스크", "플레이스테이션 5 디스크"],
    mustContain: [
      ["ps5", "플스5", "플스 5", "플레이스테이션 5", "playstation 5"],
      ["디스크", "disc"],
    ],
    mustNotContain: [
      "ps5 pro", "ps 5 pro", "플스5 프로", "플스 5 프로", "ps5pro",
      "슬림", "slim", "ps5 slim", "플스5 슬림",
      "디지털 에디션", "digital edition", "디지털에디션",
      "psvr", "psvr2", "ps vr", "vr2", "vr 2",
      "스위치", "switch", "닌텐도", "nintendo",
      "ps4", "ps3", "ps2", "ps1",
      "컨트롤러만", "듀얼센스만", "dualsense만", "충전기만", "케이스만", "스탠드만",
      "기프트", "gift card", "디지털 카드", "월정액",
      "ssd만", "ssd 단품", "카드만",
      "구합니다", "삽니다", "매입", "wts", "wtb",
      "부품용", "고장",
    ],
    msrpKrw: 698000,
    released: 2020,
  },
  {
    id: "ps5-digital-standard",
    brand: "Sony",
    category: "game_console",
    laneKey: "ps5_disc_digital_standard",
    modelName: "PlayStation 5 (Digital, Standard)",
    aliases: ["PS5 디지털", "PS5 Digital", "플스5 디지털", "플레이스테이션 5 디지털 에디션"],
    mustContain: [
      ["ps5", "플스5", "플스 5", "플레이스테이션 5", "playstation 5"],
      ["디지털", "digital"],
    ],
    mustNotContain: [
      "ps5 pro", "ps 5 pro", "플스5 프로", "플스 5 프로", "ps5pro",
      "슬림", "slim", "ps5 slim", "플스5 슬림",
      "디스크 에디션", "disc edition", "디스크에디션",
      "psvr", "psvr2", "ps vr", "vr2", "vr 2",
      "스위치", "switch", "닌텐도", "nintendo",
      "ps4", "ps3", "ps2", "ps1",
      "컨트롤러만", "듀얼센스만", "dualsense만", "충전기만", "케이스만", "스탠드만",
      "기프트", "gift card", "디지털 카드", "월정액", "psn",
      "ssd만", "ssd 단품", "카드만",
      "구합니다", "삽니다", "매입", "wts", "wtb",
      "부품용", "고장",
    ],
    msrpKrw: 568000,
    released: 2020,
  },
  // ─── AirPods ─────────────────────────────────────────
  {
    id: "airpods-2",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 2nd gen",
    aliases: ["에어팟 2세대", "AirPods 2", "에어팟2"],
    mustContain: [["에어팟", "airpods"], ["2세대", "2 세대", "2nd"]],
    mustNotContain: ["프로", "pro", "max", "맥스", "3세대", "4세대"],
    msrpKrw: 199000,
    released: 2019,
  },
  {
    id: "airpods-3",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 3rd gen",
    aliases: ["에어팟 3세대", "AirPods 3", "에어팟3"],
    mustContain: [["에어팟", "airpods"], ["3세대", "3 세대", "3rd"]],
    mustNotContain: ["프로", "pro", "max", "맥스", "2세대", "4세대"],
    msrpKrw: 269000,
    released: 2021,
  },
  {
    id: "airpods-4",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 4th gen",
    aliases: ["에어팟 4세대", "AirPods 4", "에어팟4"],
    mustContain: [["에어팟", "airpods"], ["4세대", "4 세대", "4th"]],
    mustNotContain: ["프로", "pro", "max", "맥스", "2세대", "3세대"],
    msrpKrw: 199000,
    released: 2024,
  },
  {
    id: "airpods-pro-1",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 1st gen",
    aliases: ["에어팟 프로 1세대", "AirPods Pro 1"],
    mustContain: [["에어팟", "airpods"], ["프로", "pro"], ["1세대", "1 세대", "1st"]],
    mustNotContain: ["2세대", "2nd", "max", "맥스", "usb-c", "usbc", "c타입", "타입c"],
    msrpKrw: 329000,
    released: 2019,
  },
  {
    id: "airpods-pro-2-lightning",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 2nd gen (Lightning)",
    aliases: ["에어팟 프로 2세대 라이트닝", "AirPods Pro 2 Lightning"],
    mustContain: [
      ["에어팟", "airpods"],
      ["프로", "pro"],
      ["2세대", "2 세대", "2nd", " 2 ", "프로 2", "프로2"],
    ],
    mustNotContain: ["max", "맥스", "usb-c", "usbc", "c타입", "타입c", "씨타입", "타입씨"],
    msrpKrw: 359000,
    released: 2022,
  },
  {
    id: "airpods-pro-2-usbc",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 2nd gen (USB-C)",
    aliases: ["에어팟 프로 2세대 USB-C", "AirPods Pro 2 USB-C"],
    mustContain: [
      ["에어팟", "airpods"],
      ["프로", "pro"],
      ["2세대", "2 세대", "2nd", "프로 2", "프로2"],
      ["usb-c", "usbc", "c타입", "타입c", "씨타입", "타입씨"],
    ],
    mustNotContain: ["라이트닝", "lightning", "max", "맥스"],
    msrpKrw: 359000,
    released: 2023,
  },
  {
    id: "airpods-pro-3",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 3rd gen",
    aliases: ["에어팟 프로 3세대", "AirPods Pro 3", "에어팟프로3"],
    mustContain: [
      ["에어팟", "airpods"],
      ["프로", "pro"],
      ["3세대", "3 세대", "3rd", "프로 3", "프로3"],
    ],
    mustNotContain: [
      "1세대",
      "1st",
      "2세대",
      "2nd",
      "맥스",
      "max",
      "라이트닝",
      "lightning",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 369000,
    released: 2025,
  },
  {
    id: "airpods-max",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Max (Lightning)",
    aliases: ["에어팟 맥스", "AirPods Max", "에어팟맥스"],
    mustContain: [["에어팟", "airpods"], ["맥스", "max"]],
    mustNotContain: ["usb-c", "usbc", "c타입", "타입c"],
    msrpKrw: 769000,
    released: 2020,
  },
  {
    id: "airpods-max-usbc",
    brand: "Apple",
    category: "earphone",
    laneKey: "airpods_max_usbc",
    modelName: "AirPods Max (USB-C, 2024)",
    aliases: ["에어팟 맥스 USB-C", "AirPods Max USB-C", "에어팟맥스 USB-C"],
    mustContain: [
      ["에어팟", "airpods"],
      ["맥스", "max"],
      ["usb-c", "usbc", "c타입", "타입c", "씨타입"],
    ],
    mustNotContain: ["라이트닝", "lightning", ...HEADPHONE_NOISE],
    msrpKrw: 769000,
    released: 2024,
  },
  {
    id: "sony-wh-1000xm5",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM5",
    aliases: ["소니 WH-1000XM5", "소니 XM5", "Sony WH-1000XM5"],
    mustContain: [["소니", "sony"], ["wh-1000xm5", "wh1000xm5", "xm5"]],
    mustNotContain: ["xm6", "xm4", "ult900n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 499000,
    released: 2022,
  },
  {
    id: "sony-wh-1000xm4",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM4",
    aliases: ["소니 WH-1000XM4", "소니 XM4", "Sony WH-1000XM4"],
    mustContain: [["소니", "sony"], ["wh-1000xm4", "wh1000xm4", "xm4"]],
    mustNotContain: ["xm6", "xm5", "xm3", "ult900n", "ch720n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 459000,
    released: 2020,
  },
  {
    id: "sony-wh-1000xm3",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM3",
    aliases: ["소니 WH-1000XM3", "소니 XM3", "Sony WH-1000XM3"],
    mustContain: [["소니", "sony"], ["wh-1000xm3", "wh1000xm3", "xm3"]],
    mustNotContain: ["xm6", "xm5", "xm4", "ult900n", "ch720n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 449000,
    released: 2018,
  },
  {
    id: "sony-wh-1000xm6",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM6",
    aliases: ["소니 WH-1000XM6", "소니 XM6", "Sony WH-1000XM6"],
    mustContain: [["소니", "sony"], ["wh-1000xm6", "wh1000xm6", "xm6"]],
    mustNotContain: ["xm5", "xm4", "ult900n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 599000,
    released: 2025,
  },
  {
    id: "sony-wh-ult900n",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-ULT900N / ULT Wear",
    aliases: ["소니 WH-ULT900N", "소니 ULT WEAR", "Sony ULT Wear"],
    mustContain: [["소니", "sony"], ["wh-ult900n", "wh ult900n", "whult900n", "ult900n", "ult wear", "ultwear"]],
    mustNotContain: ["1000xm", "xm3", "xm4", "xm5", "xm6", "ch720n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 259000,
    released: 2024,
  },
  {
    id: "sony-wh-ch720n",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-CH720N",
    aliases: ["소니 WH-CH720N", "Sony WH-CH720N"],
    mustContain: [["소니", "sony"], ["wh-ch720n", "wh ch720n", "whch720n", "ch720n"]],
    mustNotContain: ["1000xm", "xm3", "xm4", "xm5", "xm6", "ult900n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 199000,
    released: 2023,
  },
  {
    id: "sony-wh-ch520",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-CH520",
    aliases: ["소니 WH-CH520", "Sony WH-CH520"],
    mustContain: [["소니", "sony"], ["wh-ch520", "wh ch520", "whch520", "ch520"]],
    mustNotContain: [
      "wh-ch700n",
      "wh ch700n",
      "whch700n",
      "ch700n",
      "wh-ch710n",
      "wh ch710n",
      "whch710n",
      "ch710n",
      "wh-ch500",
      "wh ch500",
      "whch500",
      "ch500",
      "wh-1000xm",
      "xm3",
      "xm4",
      "xm5",
      "xm6",
      "ult900n",
      "ult wear",
      "ultwear",
      "linkbuds",
      "wf-",
      "wf 1000",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 79000,
    released: 2022,
  },
  {
    id: "bose-qc-ultra-headphones",
    brand: "Bose",
    category: "earphone",
    modelName: "Bose QuietComfort Ultra Headphones",
    aliases: ["보스 QC 울트라 헤드폰", "Bose QC Ultra Headphones", "Bose QuietComfort Ultra Headphones"],
    mustContain: [
      ["보스", "bose"],
      ["quietcomfort ultra", "qc ultra", "qc 울트라", "quietcomfort 울트라", "qcultra"],
      ["헤드폰", "headphone", "헤드셋"],
    ],
    mustNotContain: [
      "qc35",
      "qc 35",
      "qc45",
      "qc 45",
      "qc15",
      "qc 15",
      "qc20",
      "qc 20",
      "quietcomfort 35",
      "quietcomfort 45",
      "quietcomfort earbuds",
      "qc 이어버드",
      "qc earbuds",
      "이어버드",
      "earbuds",
      "earphone",
      "soundlink",
      "사운드링크",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 599000,
    released: 2023,
  },
  {
    id: "bose-qc45",
    brand: "Bose",
    category: "earphone",
    modelName: "Bose QuietComfort 45",
    aliases: ["보스 QC45", "Bose QC45"],
    mustContain: [["보스", "bose"], ["qc45", "qc 45", "quietcomfort 45"]],
    mustNotContain: ["울트라", "ultra", ...HEADPHONE_NOISE],
    msrpKrw: 389000,
    released: 2021,
  },
  {
    id: "beats-solo4",
    brand: "Beats",
    category: "earphone",
    modelName: "Beats Solo 4",
    aliases: ["비츠 솔로4", "Beats Solo 4"],
    mustContain: [["비츠", "beats"], ["솔로4", "solo4", "solo 4"]],
    mustNotContain: ["solo3", "solo 3", "닥터드레 ep", "ep", ...HEADPHONE_NOISE],
    msrpKrw: 269000,
    released: 2024,
  },
  {
    id: "sennheiser-accentum",
    brand: "Sennheiser",
    category: "earphone",
    modelName: "Sennheiser Accentum Wireless",
    aliases: ["젠하이저 ACCENTUM", "Sennheiser Accentum"],
    mustContain: [["젠하이저", "sennheiser"], ["accentum", "엑센텀"]],
    mustNotContain: ["hd569", "momentum", ...HEADPHONE_NOISE],
    msrpKrw: 259000,
    released: 2023,
  },
  {
    id: "sennheiser-hd569",
    brand: "Sennheiser",
    category: "earphone",
    modelName: "Sennheiser HD569",
    aliases: ["젠하이저 HD569", "Sennheiser HD569"],
    mustContain: [["젠하이저", "sennheiser"], ["hd569", "hd 569"]],
    mustNotContain: ["accentum", "momentum", ...HEADPHONE_NOISE],
    msrpKrw: 259000,
    released: 2016,
  },

  // ─── Apple Watch ─────────────────────────────────────
  {
    id: "applewatch-se1",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch SE 1st gen",
    aliases: ["애플워치 SE 1세대", "Apple Watch SE 1st gen"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["se"], ["1세대", "1 세대", "1st"]],
    mustNotContain: ["se2", "se 2", "se3", "se 3", "ultra", "series", "시리즈"],
    msrpKrw: 359000,
    released: 2020,
  },
  {
    id: "applewatch-se2",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch SE 2nd gen",
    aliases: ["애플워치 SE 2세대", "애플워치 SE2", "Apple Watch SE 2"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["se2", "se 2", "se 2세대", "se 2nd"]],
    mustNotContain: ["se3", "se 3", "ultra"],
    msrpKrw: 359000,
    released: 2022,
  },
  {
    id: "applewatch-se3",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch SE 3rd gen",
    aliases: ["애플워치 SE3", "애플워치 SE 3세대", "Apple Watch SE 3"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["se3", "se 3", "se 3세대", "se 3rd"]],
    mustNotContain: ["se2", "se 2", "ultra"],
    msrpKrw: 359000,
    released: 2025,
  },
  {
    id: "applewatch-series7",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 7",
    aliases: ["애플워치 7", "애플워치 시리즈 7", "Apple Watch Series 7"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 7", "series 7", " 7 ", "s7", "워치7", "워치 7"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 8", "시리즈 9", "시리즈 10", "series 8", "series 9", "series 10"],
    msrpKrw: 539000,
    released: 2021,
  },
  {
    id: "applewatch-series8",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 8",
    aliases: ["애플워치 8", "애플워치 시리즈 8", "Apple Watch Series 8"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 8", "series 8", " 8 ", "s8", "워치8", "워치 8"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 7", "시리즈 9", "시리즈 10", "series 7", "series 9", "series 10"],
    msrpKrw: 599000,
    released: 2022,
  },
  {
    id: "applewatch-series9",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 9",
    aliases: ["애플워치 9", "애플워치 시리즈 9", "Apple Watch Series 9"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 9", "series 9", " 9 ", "s9", "워치9", "워치 9"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 7", "시리즈 8", "시리즈 10", "series 7", "series 8", "series 10"],
    msrpKrw: 599000,
    released: 2023,
  },
  {
    id: "applewatch-series10",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 10",
    aliases: ["애플워치 10", "애플워치 시리즈 10", "Apple Watch Series 10"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 10", "series 10", " 10 ", "s10", "워치10", "워치 10"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 7", "시리즈 8", "시리즈 9", "series 7", "series 8", "series 9"],
    msrpKrw: 599000,
    released: 2024,
  },
  {
    id: "applewatch-ultra",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Ultra",
    aliases: ["애플워치 울트라", "Apple Watch Ultra"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["울트라", "ultra"]],
    mustNotContain: ["울트라 2", "ultra 2"],
    msrpKrw: 1149000,
    released: 2022,
  },
  {
    id: "applewatch-ultra2",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Ultra 2",
    aliases: ["애플워치 울트라 2", "Apple Watch Ultra 2"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["울트라 2", "ultra 2"]],
    mustNotContain: [],
    msrpKrw: 1149000,
    released: 2023,
  },

  // ─── Galaxy Watch ─────────────────────────────────────
  {
    id: "galaxywatch-6",
    brand: "Samsung",
    category: "smartwatch",
    modelName: "Galaxy Watch 6",
    aliases: ["갤럭시 워치 6", "갤워치 6", "Galaxy Watch 6"],
    mustContain: [
      ["갤럭시 워치", "갤워치", "galaxy watch", "갤럭시워치"],
      [" 6 ", "워치6", "워치 6"],
    ],
    mustNotContain: [" 7 ", "워치7", "ultra"],
    msrpKrw: 369000,
    released: 2023,
  },
  {
    id: "galaxywatch-7",
    brand: "Samsung",
    category: "smartwatch",
    modelName: "Galaxy Watch 7",
    aliases: ["갤럭시 워치 7", "갤워치 7", "Galaxy Watch 7"],
    mustContain: [
      ["갤럭시 워치", "갤워치", "galaxy watch", "갤럭시워치"],
      [" 7 ", "워치7", "워치 7"],
    ],
    mustNotContain: [" 6 ", "워치6", "ultra"],
    msrpKrw: 339000,
    released: 2024,
  },
  {
    id: "galaxywatch-ultra",
    brand: "Samsung",
    category: "smartwatch",
    modelName: "Galaxy Watch Ultra",
    aliases: ["갤럭시 워치 울트라", "Galaxy Watch Ultra"],
    mustContain: [
      ["갤럭시 워치", "갤워치", "galaxy watch", "갤럭시워치"],
      ["울트라", "ultra"],
    ],
    mustNotContain: [],
    msrpKrw: 829000,
    released: 2024,
  },
  ...CORE_SMARTPHONE_CATALOG,
  ...CORE_TABLET_CATALOG,
  ...CORE_LAPTOP_CATALOG,
  ...GENERATED_CATALOG_WITH_GATES,
];

const SKU_MAP = new Map(CATALOG.map((s) => [s.id, s]));
export function skuById(id: string): Sku | undefined {
  return SKU_MAP.get(id);
}

const NORMALIZATIONS: [RegExp, string][] = [
  [/usb[\s\-_]*c/gi, " usbc "],
  [/c[\s\-_]*type/gi, " usbc "],
  [/c\s*타입|타입\s*c|씨\s*타입|타입\s*씨/gi, " usbc "],
  [/1\s*세대|일\s*세대|first|1st/gi, " 1세대 "],
  [/2\s*세대|이\s*세대|second|2nd/gi, " 2세대 "],
  [/3\s*세대|삼\s*세대|third|3rd/gi, " 3세대 "],
  [/4\s*세대|사\s*세대|fourth|4th/gi, " 4세대 "],
  [/프로\s*2/gi, " 프로 프로2 2세대 "],
  [/프로\s*1/gi, " 프로 프로1 1세대 "],
  [/\bpro\s*2\b/gi, " pro pro2 2세대 "],
  [/\bpro\s*1\b/gi, " pro pro1 1세대 "],
  [/에어팟\s*([234])/g, " 에어팟 $1세대 "],
  [/에어팟프로\s*([123])/g, " 에어팟 프로$1 "],
  [/애어팟/g, " 에어팟 "],
  [/울트라\s*2/gi, " 울트라 2 "],
  [/ultra\s*2/gi, " ultra 2 "],
  [/se\s*([123])/gi, " se$1 "],
  [/시리즈\s*([0-9]+)/g, " 시리즈 $1 "],
  [/series\s*([0-9]+)/gi, " series $1 "],
  [/애플\s*워치/g, " 애플워치 "],
  [/갤럭시\s*워치/g, " 갤럭시워치 "],
  [/아이\s*패드/g, " 아이패드 "],
  [/아이패드\s*(프로|에어|미니)/g, " 아이패드 $1 "],
  [/갤럭시\s*탭/g, " 갤럭시탭 "],
  [/갤\s*탭/g, " 갤탭 "],
  [/air\s*pods/gi, " airpods "],
];

export function normalize(text: string): string {
  let t = (text ?? "").toLowerCase();
  t = t.replace(/\+/g, " plus ");
  for (const [pat, repl] of NORMALIZATIONS) {
    t = t.replace(pat, repl);
  }
  t = t.replace(/[^0-9a-z가-힣]+/g, " ").replace(/\s+/g, " ").trim();
  return ` ${t} `;
}

function tokenHit(normalizedText: string, token: string): boolean {
  const n = normalize(token).trim();
  if (!n) return false;
  if (/^\d+$/.test(n)) return normalizedText.includes(` ${n} `);
  return normalizedText.includes(n);
}

function skuMatches(sku: Sku, normalizedText: string): boolean {
  for (const group of sku.mustContain) {
    if (!group.some((token) => tokenHit(normalizedText, token))) return false;
  }
  for (const token of sku.mustNotContain) {
    if (tokenHit(normalizedText, token)) return false;
  }
  return true;
}

function stripLinkLikeText(text: string): string {
  return String(text ?? "")
    .replace(/https?:\/\/\S+/gi, " ")
    .replace(/\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b/gi, " ");
}

function directSpecificMatch(normalizedText: string): Sku | null {
  const compact = normalizedText.replace(/\s+/g, "");
  if (/(아이폰16e|iphone16e)/i.test(compact) || /iphone\s*16e/i.test(normalizedText)) {
    return skuById("iphone-16e") ?? null;
  }
  if (/(아이패드|ipad).{0,24}a17pro/i.test(compact) || /(아이패드|ipad).{0,32}a17\s*pro/i.test(normalizedText)) {
    return skuById("ipad-mini") ?? null;
  }
  return null;
}

export function ruleMatch(title: string, description = ""): Sku | null {
  const titleNorm = normalize(title);
  const titleDirect = directSpecificMatch(titleNorm);
  if (titleDirect) return titleDirect;

  const titleCandidates = CATALOG.filter((s) => skuMatches(s, titleNorm));
  if (titleCandidates.length === 1) return titleCandidates[0];
  if (titleCandidates.length > 1) return null;

  const combined = normalize(`${title} ${stripLinkLikeText(description).slice(0, 200)}`);
  const combinedDirect = directSpecificMatch(combined);
  if (combinedDirect) return combinedDirect;

  const descCandidates = CATALOG.filter((s) => skuMatches(s, combined));
  if (descCandidates.length === 1) return descCandidates[0];
  return null;
}
