// catalog_v1.py를 TypeScript로 포팅.
// 카탈로그 SKU 19개 + generated mining catalog + normalize + ruleMatch.

import { GENERATED_CATALOG } from "@/lib/generated/catalog";
// Wave 91 (2026-05-15): 일반인 친화 카테고리 확장 (신발/가방/자전거). 모두 본품만, resale ≤200만.
import { SHOE_CATALOG } from "@/lib/generated/catalog-shoe-wave91";
import { BAG_CATALOG } from "@/lib/generated/catalog-bag-wave91";
import { BIKE_CATALOG } from "@/lib/generated/catalog-bike-wave91";

export type Sku = {
  id: string;
  brand: string;
  category: "earphone" | "smartwatch" | "smartphone" | "tablet" | "laptop" | "monitor" | "speaker" | "camera" | "game_console" | "desktop" | "home_appliance" | "small_appliance" | "watch" | "sport_golf" | "shoe" | "bag" | "bike";
  modelName: string;
  aliases: string[];
  mustContain: string[][];
  mustNotContain: string[];
  msrpKrw: number;
  released: number;
  // Optional narrow-lane tag. When set, this SKU belongs to a specific runtime
  // lane (e.g. "ps5_disc_digital_standard") whose readiness in
  // `LANE_READINESS` overrides the broader category gate.
  laneKey?: string;
};

const PHONE_NOISE = [
  "케이스",
  "case",
  "폰케이스",
  "그립톡",
  "스마트톡",
  "맥세이프",
  "파인우븐",
  "슬림아머",
  "슈피겐",
  "어반소피스티케이션",
  "모란카노",
  "tyreus",
  "디월렛",
  "다이어리",
  "필름",
  "강화유리",
  "키보드",
  "키패드",
  "물리키패드",
  "충전기만",
  "어댑터만",
  "액정",
  "액정만",
  "배터리만",
  "메인보드",
  "뒷판",
  "후면유리",
  "후면 유리",
  "후면판",
  "백글라스",
  "하우징",
  "카메라렌즈",
  "카메라 렌즈",
  "충전단자",
  "줄이어폰",
  "부품용",
  "파손폰",
  "고장폰",
  "고장",
  "분실폰",
  "잠김",
  "락걸림",
  "매입",
  "삽니다",
  "구합니다",
  "구해봅니다",
  "구매함",
  "최고가",
  "대여",
  "렌탈",
  "색상교환",
  "교환하실분",
  "교환하실 분",
];

const TABLET_NOISE = [
  "케이스",
  "필름",
  "강화유리",
  "펜슬만",
  "애플펜슬만",
  "키보드만",
  "매직키보드만",
  "충전기만",
  "액정",
  "액정만",
  "배터리만",
  "부품용",
  "파손",
  "고장",
  "매입",
  "삽니다",
  "구합니다",
  "대여",
  "렌탈",
];

const HEADPHONE_NOISE = [
  "이어패드만",
  "이어 패드만",
  "이어쿠션만",
  "이어 쿠션만",
  "헤드쿠션만",
  "헤드 쿠션만",
  "케이스만",
  "파우치만",
  "거치대만",
  "스탠드만",
  "충전기만",
  "케이블만",
  "부품용",
  "고장",
  "불량",
  "삽니다",
  "구합니다",
  "매입",
];

const SPEAKER_NOISE = [
  "케이스",
  "case",
  "하드쉘",
  "파우치",
  "가방",
  "커버",
  "스탠드만",
  "거치대만",
  "충전기만",
  "케이블만",
  "마이크",
  "무선마이크",
  "노래방",
  "karaoke",
  "pa",
  "리시버",
  "receiver",
  "앰프",
  "amp",
  "사운드바",
  "soundbar",
  "일괄",
  "고장",
  "파손",
  "대여",
  "렌탈",
  "삽니다",
  "구합니다",
  "매입",
];

const CAMERA_BODY_ONLY_NOISE = [
  "렌즈",
  "lens",
  "번들",
  "번들킷",
  "키트",
  "kit",
  "세트",
  "풀셋",
  "풀셋트",
  "바디캡",
  "렌즈캡",
  "뒷캡",
  "캡",
  "케이스",
  "가방",
  "하자",
  "수리필요",
  "부품용",
  "고장",
  "구매",
  "삽니다",
  "구합니다",
  "업자x",
  "사기꾼",
  "바디프렌드",
];

// Wave 67: 시계 narrow lane noise (오리지널 본체 매물만 매칭).
// 가품/리퍼/액세서리/구매요청 거름. "줄/스트랩/베젤"은 액세서리만 명시될 때 거름 (본체+ 같이는 OK 위해 mustContain 우선).
const WATCH_NOISE = [
  "줄만", "스트랩만", "밴드만",
  "베젤만", "유리만", "쉬라우드만",
  "케이스만",
  "복각", "homage", "오마주",
  "고장", "수리필요", "부품용", "as용", "고정만",
  "삽니다", "구매합니다", "구합니다",
  "가품", "이미테이션", "fake",
  "사진용", "디스플레이용", "전시용",
];

// Wave 67: 골프 narrow lane noise (드라이버 본체 매물 — 헤드만은 별개 분기).
// 풀세트(아이언+드라이버) / 우드세트는 거름 — 드라이버 단독 매물만.
const GOLF_DRIVER_NOISE = [
  "풀세트", "풀 세트", "골프세트", "골프 세트",
  "아이언세트", "아이언 세트",
  "우드세트", "우드 세트",
  "삽니다", "구매합니다", "구합니다",
  "가품", "이미테이션", "fake",
  "수리필요", "부품용", "고장",
  "유틸",  // 유틸리티 우드 — 드라이버 아님
];

const LAPTOP_NOISE = [
  "메인보드",
  "메인 보드",
  "로직보드",
  "로직 보드",
  "상판",
  "하판",
  "액정만",
  "배터리만",
  "키보드만",
  "부품용",
  "부품",
  "고장",
  "침수",
];

const GENERATED_CATALOG_WITH_GATES: Sku[] = GENERATED_CATALOG.map((sku) => {
  if (sku.category !== "laptop") return sku;
  return {
    ...sku,
    mustNotContain: [...new Set([...sku.mustNotContain, ...LAPTOP_NOISE])],
  };
});

const CORE_SMARTPHONE_CATALOG: Sku[] = [
  {
    id: "iphone-11-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_11_pro_128gb_self",
    modelName: "iPhone 11 Pro 128GB (자급제)",
    aliases: ["아이폰 11 프로 128 자급제", "iPhone 11 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 11 프로", "아이폰11프로", "iphone 11 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 10", "iphone 10", "아이폰10",
      "아이폰 12", "iphone 12", "아이폰12",
      "xs", "xr",
      "64gb", "64 gb", "64기가",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1390000,
    released: 2019,
  },
  {
    id: "iphone-12-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_12_pro_128gb_self",
    modelName: "iPhone 12 Pro 128GB (자급제)",
    aliases: ["아이폰 12 프로 128 자급제", "iPhone 12 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 12 프로", "아이폰12프로", "iphone 12 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "미니", "mini",
      "플러스", "plus",
      "아이폰 11", "iphone 11", "아이폰11",
      "아이폰 13", "iphone 13", "아이폰13",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1350000,
    released: 2020,
  },
  {
    id: "iphone-13-pro",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 13 Pro",
    aliases: ["아이폰 13 프로", "아이폰13프로", "iPhone 13 Pro"],
    mustContain: [["아이폰 13 프로", "아이폰13프로", "iphone 13 pro"]],
    mustNotContain: ["프로맥스", "프로 맥스", "promax", "프맥", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1350000,
    released: 2021,
  },
  {
    id: "iphone-13-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_13_pro_128gb_self",
    modelName: "iPhone 13 Pro 128GB (자급제)",
    aliases: ["아이폰 13 프로 128 자급제", "iPhone 13 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 13 프로", "아이폰13프로", "iphone 13 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 12", "iphone 12", "아이폰12",
      "아이폰 14", "iphone 14", "아이폰14",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1350000,
    released: 2021,
  },
  {
    id: "iphone-13-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 13 Pro Max",
    aliases: ["아이폰 13 프로맥스", "아이폰13프로맥스", "iPhone 13 Pro Max"],
    mustContain: [["아이폰 13 프로맥스", "아이폰13프로맥스", "아이폰 13 프로 맥스", "iphone 13 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1490000,
    released: 2021,
  },
  {
    id: "iphone-14-pro",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 14 Pro",
    aliases: ["아이폰 14 프로", "아이폰14프로", "iPhone 14 Pro"],
    mustContain: [["아이폰 14 프로", "아이폰14프로", "iphone 14 pro"]],
    mustNotContain: ["프로맥스", "프로 맥스", "promax", "프맥", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1550000,
    released: 2022,
  },
  {
    id: "iphone-14-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_14_pro_128gb_self",
    modelName: "iPhone 14 Pro 128GB (자급제)",
    aliases: ["아이폰 14 프로 128 자급제", "iPhone 14 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 14 프로", "아이폰14프로", "iphone 14 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 13", "iphone 13", "아이폰13",
      "아이폰 15", "iphone 15", "아이폰15",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1550000,
    released: 2022,
  },
  {
    id: "iphone-14-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 14 Pro Max",
    aliases: ["아이폰 14 프로맥스", "아이폰14프로맥스", "iPhone 14 Pro Max"],
    mustContain: [["아이폰 14 프로맥스", "아이폰14프로맥스", "아이폰 14 프로 맥스", "iphone 14 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1750000,
    released: 2022,
  },
  {
    id: "iphone-15-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 15 Pro Max",
    aliases: ["아이폰 15 프로맥스", "아이폰15프로맥스", "iPhone 15 Pro Max"],
    mustContain: [["아이폰 15 프로맥스", "아이폰15프로맥스", "아이폰 15 프로 맥스", "iphone 15 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1900000,
    released: 2023,
  },
  {
    id: "iphone-15-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_15_pro_128gb_self",
    modelName: "iPhone 15 Pro 128GB (자급제)",
    aliases: ["아이폰 15 프로 128 자급제", "iPhone 15 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 15 프로", "아이폰15프로", "iphone 15 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 14", "iphone 14", "아이폰14",
      "아이폰 16", "iphone 16", "아이폰16",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1550000,
    released: 2023,
  },
  {
    id: "iphone-16e",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 16e",
    aliases: ["아이폰 16e", "아이폰16e", "iPhone 16e"],
    mustContain: [["아이폰 16e", "아이폰16e", "iphone 16e"]],
    mustNotContain: ["프로", "pro", "프로맥스", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 990000,
    released: 2025,
  },
  {
    id: "iphone-16-pro",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 16 Pro",
    aliases: ["아이폰 16 프로", "아이폰16프로", "iPhone 16 Pro"],
    mustContain: [["아이폰 16 프로", "아이폰16프로", "iphone 16 pro"]],
    mustNotContain: ["프로맥스", "프로 맥스", "promax", "프맥", "pro max", "플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1550000,
    released: 2024,
  },
  {
    id: "iphone-16-pro-128-self",
    brand: "Apple",
    category: "smartphone",
    laneKey: "iphone_16_pro_128gb_self",
    modelName: "iPhone 16 Pro 128GB (자급제)",
    aliases: ["아이폰 16 프로 128 자급제", "iPhone 16 Pro 128 SIM-Free"],
    mustContain: [
      ["아이폰 16 프로", "아이폰16프로", "iphone 16 pro"],
      ["128gb", "128 gb", "128기가", "128g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "프로맥스", "pro max", "promax", "프맥", "프로 맥스",
      "플러스", "plus",
      "아이폰 15", "iphone 15", "아이폰15",
      "아이폰 17", "iphone 17", "아이폰17",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1550000,
    released: 2024,
  },
  {
    id: "iphone-16-pro-max",
    brand: "Apple",
    category: "smartphone",
    modelName: "iPhone 16 Pro Max",
    aliases: ["아이폰 16 프로맥스", "아이폰16프로맥스", "iPhone 16 Pro Max"],
    mustContain: [["아이폰 16 프로맥스", "아이폰16프로맥스", "아이폰 16 프로 맥스", "iphone 16 pro max"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1900000,
    released: 2024,
  },
  {
    id: "galaxy-s23-ultra",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S23 Ultra",
    aliases: ["갤럭시 S23 울트라", "갤럭시S23울트라", "Galaxy S23 Ultra"],
    mustContain: [["갤럭시 s23 울트라", "갤럭시s23울트라", "galaxy s23 ultra", "s23 ultra"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1600000,
    released: 2023,
  },
  {
    id: "galaxy-s24-ultra",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S24 Ultra",
    aliases: ["갤럭시 S24 울트라", "갤럭시S24울트라", "Galaxy S24 Ultra"],
    mustContain: [["갤럭시 s24 울트라", "갤럭시s24울트라", "galaxy s24 ultra", "s24 ultra"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1700000,
    released: 2024,
  },
  {
    id: "galaxy-s24-ultra-256-self",
    brand: "Samsung",
    category: "smartphone",
    laneKey: "galaxy_s24_ultra_256_self",
    modelName: "Galaxy S24 Ultra 256GB (자급제)",
    aliases: ["갤럭시 S24 울트라 256 자급제", "Galaxy S24 Ultra 256 SIM-Free"],
    mustContain: [
      ["갤럭시 s24 울트라", "갤럭시s24울트라", "galaxy s24 ultra", "s24 ultra"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "s23", "갤럭시 s23", "galaxy s23",
      "s25", "갤럭시 s25", "galaxy s25",
      "플러스", "plus", "일반", "basic",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1700000,
    released: 2024,
  },
  {
    id: "galaxy-s25",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S25",
    aliases: ["갤럭시 S25", "갤럭시S25", "Galaxy S25"],
    mustContain: [["갤럭시 s25", "갤럭시s25", "galaxy s25", "s25"]],
    mustNotContain: ["울트라", "ultra", "플러스", "plus", "fe", "팬에디션", "gs25", ...PHONE_NOISE],
    msrpKrw: 1150000,
    released: 2025,
  },
  {
    id: "galaxy-s25-plus",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S25 Plus",
    aliases: ["갤럭시 S25 플러스", "갤럭시S25플러스", "Galaxy S25 Plus"],
    mustContain: [["갤럭시 s25 플러스", "갤럭시s25플러스", "galaxy s25 plus", "s25 plus"]],
    mustNotContain: ["울트라", "ultra", ...PHONE_NOISE],
    msrpKrw: 1350000,
    released: 2025,
  },
  {
    id: "galaxy-s25-ultra",
    brand: "Samsung",
    category: "smartphone",
    modelName: "Galaxy S25 Ultra",
    aliases: ["갤럭시 S25 울트라", "갤럭시S25울트라", "Galaxy S25 Ultra"],
    mustContain: [["갤럭시 s25 울트라", "갤럭시s25울트라", "galaxy s25 ultra", "s25 ultra"]],
    mustNotContain: ["플러스", "plus", ...PHONE_NOISE],
    msrpKrw: 1700000,
    released: 2025,
  },
  {
    id: "galaxy-s25-ultra-256-self",
    brand: "Samsung",
    category: "smartphone",
    laneKey: "galaxy_s25_ultra_256_self",
    modelName: "Galaxy S25 Ultra 256GB (자급제)",
    aliases: ["갤럭시 S25 울트라 256 자급제", "Galaxy S25 Ultra 256 SIM-Free"],
    mustContain: [
      ["갤럭시 s25 울트라", "갤럭시s25울트라", "galaxy s25 ultra", "s25 ultra"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "s24", "갤럭시 s24", "galaxy s24",
      "s23", "갤럭시 s23", "galaxy s23",
      "s26", "갤럭시 s26", "galaxy s26",
      "플러스", "plus", "일반", "basic",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1700000,
    released: 2025,
  },
  {
    id: "galaxy-s23-ultra-256-self",
    brand: "Samsung",
    category: "smartphone",
    laneKey: "galaxy_s23_ultra_256_self",
    modelName: "Galaxy S23 Ultra 256GB (자급제)",
    aliases: ["갤럭시 S23 울트라 256 자급제", "Galaxy S23 Ultra 256 SIM-Free"],
    mustContain: [
      ["갤럭시 s23 울트라", "갤럭시s23울트라", "galaxy s23 ultra", "s23 ultra"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "s22", "갤럭시 s22", "galaxy s22",
      "s24", "갤럭시 s24", "galaxy s24",
      "s25", "갤럭시 s25", "galaxy s25",
      "s26", "갤럭시 s26", "galaxy s26",
      "플러스", "plus", "일반", "basic",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1600000,
    released: 2023,
  },
  {
    id: "galaxy-z-flip-5-256-self",
    brand: "Samsung",
    category: "smartphone",
    laneKey: "galaxy_z_flip_5_256_self",
    modelName: "Galaxy Z Flip 5 256GB (자급제)",
    aliases: ["갤럭시 Z 플립5 256 자급제", "Galaxy Z Flip 5 256 SIM-Free"],
    // 변형 흡수만 추가 (같은 의미 다른 표현). 자급제 group은 정확성 우선 원칙으로 유지 —
    // 명시 안 된 매물은 lane 진입 금지. "256" 단독은 가격 텍스트와 충돌 risk → 제거.
    mustContain: [
      ["갤럭시 z 플립", "갤럭시z플립", "갤럭시 플립", "갤럭시플립", "galaxy z flip", "galaxyzflip", "z flip", "zflip"],
      ["플립5", "플립 5", "flip5", "flip 5", "5세대"],
      ["256gb", "256 gb", "256g", "256기가"],
      ["자급제", "자급", "공기계", "언락"],
    ],
    mustNotContain: [
      "플립4", "플립 4", "flip 4",
      "플립6", "flip 6",
      "폴드", "fold",
      "512gb", "512 gb", "512g", "1tb",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...PHONE_NOISE,
    ],
    msrpKrw: 1399000,
    released: 2023,
  },
];

const CORE_LAPTOP_CATALOG_PRO: Sku[] = [
  {
    id: "macbook-pro-14-m3-18-512",
    brand: "Apple",
    category: "laptop",
    laneKey: "macbook_pro_14_m3_18_512",
    modelName: "MacBook Pro 14\" M3 18GB 512GB",
    aliases: ["맥북 프로 14 M3 18 512", "MacBook Pro 14 M3 18GB 512GB"],
    mustContain: [
      ["맥북", "macbook"],
      ["프로", "pro"],
      ["m3"],
      ["14인치", "14 인치", "14형", "14\""],
    ],
    mustNotContain: [
      "에어", "air",
      "16인치", "16형",
      "(m1)", "(m2)", "(m4)",
      " m1 ", " m2 ", " m4 ",
      // 8GB exclusion intentionally omitted: tokenHit is substring-based and would
      // self-reject "18gb"/"18 gb"/"18기가". 8GB base units are filtered by the
      // lane mining regex and the candidate-pool price range (1.5M~3M).
      "16gb", "16 gb",
      "24gb",
      "36gb",
      "256gb", "256 gb",
      "1tb", "2tb",
      "메인보드", "로직보드", "상판", "하판",
      "액정만", "배터리만", "키보드만",
      "부품", "고장", "침수",
      "매입", "삽니다",
    ],
    msrpKrw: 2690000,
    released: 2023,
  },
];

const CORE_TABLET_CATALOG: Sku[] = [
  {
    id: "ipad-pro",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad Pro",
    aliases: ["아이패드 프로", "아이패드프로", "iPad Pro"],
    mustContain: [["아이패드", "ipad"], ["프로", "pro"]],
    mustNotContain: ["에어", "air", "미니", "mini", "a17pro", "a17 pro", ...TABLET_NOISE],
    msrpKrw: 1500000,
    released: 2024,
  },
  {
    id: "ipad-pro-11-m4-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_pro_11_m4_256_wifi",
    modelName: "iPad Pro 11\" M4 256GB Wi-Fi",
    aliases: ["아이패드 프로 11 M4 256", "iPad Pro 11 M4 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["프로", "pro"],
      ["m4"],
      ["256gb", "256 gb", "256기가", "256g", "256"],
      ["11인치", "11 인치", "11형", "11\"", "11″"],
    ],
    mustNotContain: [
      "에어", "air", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"", "12.9인치", "12.9 인치", "12.9\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "2tb", "2 tb", "2테라",
      "(m1)", "(m2)", "(m3)", " m1 ", " m2 ", " m3 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1899000,
    released: 2024,
  },
  {
    id: "ipad-pro-11-m2-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_pro_11_m2_256_wifi",
    modelName: "iPad Pro 11\" M2 256GB Wi-Fi",
    aliases: ["아이패드 프로 11 M2 256", "iPad Pro 11 M2 256GB Wi-Fi", "아이패드 프로 4세대 11 256"],
    mustContain: [
      ["아이패드", "ipad"],
      ["프로", "pro"],
      ["m2"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["11인치", "11 인치", "11형", "11\"", "11″"],
    ],
    mustNotContain: [
      "에어", "air", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"", "12.9인치", "12.9 인치", "12.9\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "2tb", "2 tb", "2테라",
      "(m1)", "(m3)", "(m4)", " m1 ", " m3 ", " m4 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1399000,
    released: 2022,
  },
  {
    id: "ipad-pro-13-m4-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_pro_13_m4_256_wifi",
    modelName: "iPad Pro 13\" M4 256GB Wi-Fi",
    aliases: ["아이패드 프로 13 M4 256", "iPad Pro 13 M4 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["프로", "pro"],
      ["m4"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["13인치", "13 인치", "13형", "13\"", "13″"],
    ],
    mustNotContain: [
      "에어", "air", "미니", "mini",
      "11인치", "11 인치", "11형", "11\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb",
      "1tb", "2tb",
      "(m1)", "(m2)", "(m3)", " m1 ", " m2 ", " m3 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 2399000,
    released: 2024,
  },
  {
    id: "ipad-pro-13-m2-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_pro_13_m2_256_wifi",
    modelName: "iPad Pro 13\" M2 256GB Wi-Fi",
    aliases: ["아이패드 프로 13 M2 256", "iPad Pro 13 M2 256GB Wi-Fi", "아이패드 프로 12.9 M2 256", "아이패드 프로 6세대 256"],
    mustContain: [
      ["아이패드", "ipad"],
      ["프로", "pro"],
      ["m2"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["13인치", "13 인치", "13형", "13\"", "12.9인치", "12.9 인치"],
    ],
    mustNotContain: [
      "에어", "air", "미니", "mini",
      "11인치", "11 인치", "11형", "11\"",
      "셀룰러", "cellular", "유심", "esim",
      "128gb", "128 gb",
      "512gb", "1tb", "2tb",
      "(m1)", "(m3)", "(m4)", " m1 ", " m3 ", " m4 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1899000,
    released: 2022,
  },
  {
    id: "ipad-air",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad Air",
    aliases: ["아이패드 에어", "아이패드에어", "iPad Air"],
    mustContain: [["아이패드", "ipad"], ["에어", "air"]],
    mustNotContain: ["프로", "pro", "미니", "mini", ...TABLET_NOISE],
    msrpKrw: 900000,
    released: 2024,
  },
  {
    id: "ipad-air-m2-11-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_air_m2_11_256_wifi",
    modelName: "iPad Air M2 11\" 256GB Wi-Fi",
    aliases: ["아이패드 에어 11 M2 256", "iPad Air 11 M2 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["에어", "air"],
      ["m2"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["11인치", "11 인치", "11형", "11\"", "11″"],
    ],
    mustNotContain: [
      "프로", "pro", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"", "12.9인치", "12.9 인치", "12.9\"",
      "셀룰러", "cellular", " lte ", " 5g ", "유심", "esim",
      "128gb", "128 gb", "128기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "2tb", "2 tb", "2테라",
      "(m1)", "(m3)", " m1 ", " m3 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 999000,
    released: 2024,
  },
  {
    id: "ipad-air-m3-11-256-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_air_m3_11_256_wifi",
    modelName: "iPad Air M3 11\" 256GB Wi-Fi",
    aliases: ["아이패드 에어 11 M3 256", "iPad Air 11 M3 256GB Wi-Fi"],
    mustContain: [
      ["아이패드", "ipad"],
      ["에어", "air"],
      ["m3"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["11인치", "11 인치", "11형", "11\""],
    ],
    mustNotContain: [
      "프로", "pro", "미니", "mini",
      "13인치", "13 인치", "13형", "13\"",
      "셀룰러", "cellular", "유심", "esim",
      "128gb", "128 gb",
      "512gb", "1tb", "2tb",
      "(m1)", "(m2)", "(m4)", " m1 ", " m2 ", " m4 ",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1099000,
    released: 2025,
  },
  {
    id: "ipad-mini",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad mini",
    aliases: ["아이패드 미니", "아이패드미니", "iPad mini"],
    mustContain: [["아이패드", "ipad"], ["미니", "mini"]],
    mustNotContain: ["프로", "pro", "에어", "air", ...TABLET_NOISE],
    msrpKrw: 750000,
    released: 2024,
  },
  {
    id: "ipad-mini-7-128-wifi",
    brand: "Apple",
    category: "tablet",
    laneKey: "ipad_mini_7_128_wifi",
    modelName: "iPad mini 7 (A17 Pro) 128GB Wi-Fi",
    aliases: ["아이패드 미니 7 128", "iPad mini 7 128GB Wi-Fi", "아이패드 미니 A17 128"],
    mustContain: [
      ["아이패드", "ipad"],
      ["미니", "mini"],
      ["a17", "7세대", "7 세대", "ipad mini 7", "미니 7", "미니7"],
      ["128gb", "128 gb", "128기가", "128g"],
    ],
    mustNotContain: [
      "프로", "pro", "에어", "air",
      "미니 6", "mini 6", "미니6",
      "미니 5", "mini 5", "미니4",
      "6세대", "5세대",
      "셀룰러", "cellular", "유심", "esim",
      "256gb", "256 gb", "256기가",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      ...TABLET_NOISE,
    ],
    msrpKrw: 749000,
    released: 2024,
  },
  {
    id: "ipad-10",
    brand: "Apple",
    category: "tablet",
    modelName: "iPad 10th gen",
    aliases: ["아이패드 10세대", "아이패드10세대", "iPad 10th gen"],
    mustContain: [["아이패드", "ipad"], ["10세대", "10 세대", "10th", "ipad 10"]],
    mustNotContain: ["프로", "pro", "에어", "air", "미니", "mini", ...TABLET_NOISE],
    msrpKrw: 680000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s8",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S8",
    aliases: ["갤럭시탭 S8", "갤탭 S8", "Galaxy Tab S8"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s8", "s 8"]],
    mustNotContain: ["s8 울트라", "s8 ultra", "s8 플러스", "s8 plus", ...TABLET_NOISE],
    msrpKrw: 900000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s8-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S8 Plus",
    aliases: ["갤럭시탭 S8 플러스", "갤탭 S8+", "Galaxy Tab S8 Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s8", "s 8"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 1100000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s8-ultra",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S8 Ultra",
    aliases: ["갤럭시탭 S8 울트라", "갤탭 S8 울트라", "Galaxy Tab S8 Ultra"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s8", "s 8"], ["울트라", "ultra"]],
    mustNotContain: ["플러스", "plus", ...TABLET_NOISE],
    msrpKrw: 1400000,
    released: 2022,
  },
  {
    id: "galaxy-tab-s9",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9",
    aliases: ["갤럭시탭 S9", "갤탭 S9", "Galaxy Tab S9"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"]],
    mustNotContain: ["s9 울트라", "s9 ultra", "s9 플러스", "s9 plus", "fe", "팬에디션", ...TABLET_NOISE],
    msrpKrw: 1000000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-fe",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 FE",
    aliases: ["갤럭시탭 S9 FE", "갤탭 S9 FE", "Galaxy Tab S9 FE"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["fe", "팬에디션"]],
    mustNotContain: ["플러스", "plus", "울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 629000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-fe-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 FE Plus",
    aliases: ["갤럭시탭 S9 FE 플러스", "갤탭 S9 FE+", "Galaxy Tab S9 FE Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["fe", "팬에디션"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 799000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 Plus",
    aliases: ["갤럭시탭 S9 플러스", "갤탭 S9+", "Galaxy Tab S9 Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", "fe", "팬에디션", ...TABLET_NOISE],
    msrpKrw: 1200000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s9-ultra",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S9 Ultra",
    aliases: ["갤럭시탭 S9 울트라", "갤탭 S9 울트라", "Galaxy Tab S9 Ultra"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s9", "s 9"], ["울트라", "ultra"]],
    mustNotContain: ["플러스", "plus", ...TABLET_NOISE],
    msrpKrw: 1600000,
    released: 2023,
  },
  {
    id: "galaxy-tab-s10-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S10 Plus",
    aliases: ["갤럭시탭 S10 플러스", "갤탭 S10+", "Galaxy Tab S10 Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s10", "s 10"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", "fe", "팬에디션", ...TABLET_NOISE],
    msrpKrw: 1250000,
    released: 2024,
  },
  {
    id: "galaxy-tab-s10-fe-plus",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S10 FE Plus",
    aliases: ["갤럭시탭 S10 FE 플러스", "갤탭 S10 FE+", "Galaxy Tab S10 FE Plus"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s10", "s 10"], ["fe", "팬에디션"], ["플러스", "plus", "+"]],
    mustNotContain: ["울트라", "ultra", ...TABLET_NOISE],
    msrpKrw: 899000,
    released: 2025,
  },
  {
    id: "galaxy-tab-s10-ultra",
    brand: "Samsung",
    category: "tablet",
    modelName: "Galaxy Tab S10 Ultra",
    aliases: ["갤럭시탭 S10 울트라", "갤탭 S10 울트라", "Galaxy Tab S10 Ultra"],
    mustContain: [["갤럭시탭", "갤탭", "galaxy tab", "tab"], ["s10", "s 10"], ["울트라", "ultra"]],
    mustNotContain: ["플러스", "plus", ...TABLET_NOISE],
    msrpKrw: 1700000,
    released: 2024,
  },
  {
    id: "galaxy-tab-s10-ultra-256-self",
    brand: "Samsung",
    category: "tablet",
    laneKey: "galaxy_tab_s10_ultra_256_self",
    modelName: "Galaxy Tab S10 Ultra 256GB Wi-Fi (자급제)",
    aliases: [
      "갤럭시탭 S10 울트라 256 자급제",
      "갤탭 S10 울트라 256 와이파이",
      "Galaxy Tab S10 Ultra 256 Wi-Fi",
    ],
    mustContain: [
      ["갤럭시탭", "갤탭", "galaxy tab", "tab"],
      ["s10", "s 10"],
      ["울트라", "ultra"],
      ["256gb", "256 gb", "256기가", "256g"],
      ["자급제", "자급", "wifi", "와이파이"],
    ],
    mustNotContain: [
      "플러스", "plus",
      "fe", "팬에디션",
      "s9", "갤럭시탭 s9", "갤탭 s9", "galaxy tab s9", "tab s9",
      "s11", "갤럭시탭 s11", "갤탭 s11", "galaxy tab s11", "tab s11",
      "셀룰러", "cellular", "5g", "lte", "유심",
      "512gb", "512 gb", "512기가",
      "1tb", "1 tb", "1테라",
      "skt 완납", "skt 개통", "skt 약정", "skt 전용",
      "kt 완납", "kt 개통", "kt 약정", "kt 전용",
      "lgu+", "lg u+", "유플러스", "엘지유플",
      "통신사 개통", "통신사 전용", "번호 이동", "약정 승계",
      "완납폰", "완납 폰", "할부 승계", "할부 잔여", "확정 기변",
      "리퍼폰", "리퍼 폰",
      ...TABLET_NOISE,
    ],
    msrpKrw: 1700000,
    released: 2024,
  },
];

const CORE_LAPTOP_CATALOG: Sku[] = [
  {
    id: "macbook-air-m2-13-256",
    brand: "Apple",
    category: "laptop",
    laneKey: "macbook_air_m2_13_256",
    modelName: "MacBook Air M2 13\" 256GB",
    aliases: ["맥북 에어 M2 13 256", "MacBook Air M2 13\" 256GB"],
    mustContain: [
      ["맥북", "macbook"],
      ["에어", "air"],
      ["m2"],
      ["13인치", "13 인치", "13형", "13\""],
      ["8gb", "8 gb", "8기가", "8램", "8g", "기본형", "기본 모델", "깡통"],
    ],
    mustNotContain: [
      "프로", "pro",
      "15인치", "15형",
      "(m1)", "(m3)", "(m4)",
      " m1 ", " m3 ", " m4 ",
      "16gb", "16 gb", "16기가", "16램",
      "24gb", "24 gb", "24기가", "24램",
      "512gb", "512 gb", "512기가", "512",
      "1tb", "1 tb", "1테라",
      "메인보드", "로직보드", "상판", "하판",
      "액정만", "배터리만", "키보드만",
      "빈박스", "박스만", "보호필름", "필름", "케이스만", "파우치",
      "교환", "교신",
      "부품", "고장", "침수",
      "매입", "삽니다",
    ],
    msrpKrw: 1690000,
    released: 2022,
  },
  {
    id: "macbook-air-m3-13-256",
    brand: "Apple",
    category: "laptop",
    laneKey: "macbook_air_m3_13_256",
    modelName: "MacBook Air M3 13\" 256GB",
    aliases: ["맥북 에어 M3 13 256", "MacBook Air M3 13\" 256GB"],
    mustContain: [
      ["맥북", "macbook"],
      ["에어", "air"],
      ["m3"],
      ["13인치", "13 인치", "13형", "13\""],
    ],
    mustNotContain: [
      "프로", "pro",
      "15인치", "15형",
      "(m1)", "(m2)", "(m4)",
      " m1 ", " m2 ", " m4 ",
      "메인보드", "로직보드", "상판", "하판",
      "액정만", "배터리만", "키보드만",
      "부품", "고장", "침수",
      "매입", "삽니다",
    ],
    msrpKrw: 1390000,
    released: 2024,
  },
  {
    id: "lg-gram-17-2024",
    brand: "LG",
    category: "laptop",
    laneKey: "lg_gram_17_2024",
    modelName: "LG Gram 17\" 2024 (16GB / 512GB)",
    aliases: ["LG 그램 17 2024", "엘지 그램 17 2024", "LG Gram 17 2024"],
    mustContain: [
      ["lg 그램", "lg그램", "lg전자 그램", "lg전자그램", "엘지 그램", "엘지그램", "lg gram"],
      ["17인치", "17 인치", "17형", "17\"", "17z90s", "17zd90s", "17zd90su"],
      ["2024", "13세대", "14세대", "ultra 7", "ultra 5", "코어울트라", "17z90s", "17zd90s", "17zd90su"],
    ],
    mustNotContain: [
      "14인치", "14 인치", "14형",
      "15인치", "15 인치", "15형",
      "16인치", "16형",
      "2 in 1", "2in1",
      "gram pro", "그램프로", "그램 프로",
      "17z90sp", "17zd90sp", "17z90tr", "17zd90tr",
      "17z90r", "17zd90r", "17z90p", "17zd90p", "17z90q", "17zd90q", "17z90u", "17zd90u", "17zd90ru",
      "2023", "2022", "2021", "2020", "2019",
      "액정만", "메인보드", "부품", "고장", "침수",
      "매입", "삽니다",
    ],
    msrpKrw: 1990000,
    released: 2024,
  },
];

export const CATALOG: Sku[] = [
  // ─── Monitor exact model-code review candidates ─────
  {
    id: "monitor-xl2540k",
    brand: "BenQ ZOWIE",
    category: "monitor",
    laneKey: "monitor_benq_xl2540k",
    modelName: "BenQ ZOWIE XL2540K",
    aliases: ["XL2540K", "벤큐 XL2540K", "ZOWIE XL2540K"],
    mustContain: [["xl2540k"]],
    mustNotContain: [],
    msrpKrw: 499000,
    released: 2020,
  },
  {
    id: "monitor-27us550",
    brand: "LG",
    category: "monitor",
    modelName: "LG 27US550",
    aliases: ["27US550", "LG 27US550", "27US550-W"],
    mustContain: [["27us550"]],
    mustNotContain: [],
    msrpKrw: 399000,
    released: 2024,
  },
  {
    id: "monitor-ls27f354fhk",
    brand: "Samsung",
    category: "monitor",
    modelName: "Samsung LS27F354FHK",
    aliases: ["LS27F354FHK", "삼성 LS27F354FHK"],
    mustContain: [["ls27f354fhk"]],
    mustNotContain: [],
    msrpKrw: 249000,
    released: 2016,
  },
  {
    id: "monitor-39gx900a",
    brand: "LG",
    category: "monitor",
    modelName: "LG 39GX900A",
    aliases: ["39GX900A", "39GX900A-B", "LG 39GX900A"],
    mustContain: [["39gx900a"]],
    mustNotContain: [],
    msrpKrw: 2190000,
    released: 2025,
  },
  {
    id: "monitor-aw2525hm",
    brand: "Dell Alienware",
    category: "monitor",
    modelName: "Dell Alienware AW2525HM",
    aliases: ["AW2525HM", "Alienware AW2525HM"],
    mustContain: [["aw2525hm"]],
    mustNotContain: [],
    msrpKrw: 499000,
    released: 2025,
  },
  {
    // Wave 24: LG 27UP850N-W (UltraFine 4K, USB-C 90W, 2022 refresh). msrp 약 650k.
    // 중고 시세 255~500k (Bunjang 7 collected). UP850 / UP850N / UP850K 변형 포함 (동일 form factor).
    id: "monitor-27up850n",
    brand: "LG",
    category: "monitor",
    laneKey: "monitor_lg_27up850n",
    modelName: "LG 27UP850N-W",
    aliases: ["27UP850N", "27UP850", "27UP850K", "27UP850N-W", "LG 27UP850N", "LG 27UP850", "LG UltraFine 27UP850"],
    mustContain: [["27up850"]],
    mustNotContain: [
      // 다른 LG 4K monitor 변형 분리
      "27ul850", "27uk850", "27up550", "27up600", "27us550",
      // gaming 27GP850과 격리
      "27gp850", "27gn850", "ultragear", "울트라기어",
      // 32"/24" 다른 사이즈
      "32up850", "32up", "24up",
      // 부품/단품/하자
      "스탠드만", "거치대만", "케이블만", "어댑터만", "부품용", "파손", "고장", "수리이력", "액정파손",
      "매입", "삽니다", "구해요", "구매합니다", "구합니다",
    ],
    msrpKrw: 650000,
    released: 2022,
  },
  {
    // Wave 24 fallback: LG 27GP850-B (UltraGear QHD 165Hz Nano IPS, 2021). msrp 590k.
    // 27UP850N의 distribution 너무 좁음(356~380k)으로 fallback. 중고 240~340k wider.
    id: "monitor-27gp850",
    brand: "LG",
    category: "monitor",
    laneKey: "monitor_lg_27gp850",
    modelName: "LG UltraGear 27GP850-B",
    aliases: ["27GP850", "27GP850-B", "LG 27GP850", "LG UltraGear 27GP850", "엘지 울트라기어 27GP850"],
    mustContain: [["27gp850"]],
    mustNotContain: [
      // 다른 LG UltraGear gaming 변형 격리
      "27gn850", "27gn800", "27gp83", "27gp95", "27gp700",
      // UltraFine 4K 라인업과 격리
      "27up850", "27ul850", "27uk850",
      // 32"/24" 다른 사이즈
      "32gp850", "24gp850",
      // 부품/단품/하자
      "스탠드만", "거치대만", "케이블만", "어댑터만", "부품용", "파손", "고장", "수리이력", "액정파손",
      "매입", "삽니다", "구해요", "구매합니다", "구합니다",
    ],
    msrpKrw: 590000,
    released: 2021,
  },
  {
    id: "monitor-27gl650f",
    brand: "LG",
    category: "monitor",
    modelName: "LG UltraGear 27GL650F",
    aliases: ["27GL650F", "LG 27GL650F", "울트라기어 27GL650F"],
    mustContain: [["27gl650f"]],
    mustNotContain: [],
    msrpKrw: 399000,
    released: 2019,
  },
  // ─── Portable Bluetooth speaker exact-model review candidates ───
  {
    id: "speaker-jbl-go-3",
    brand: "JBL",
    category: "speaker",
    modelName: "JBL GO 3",
    aliases: ["JBL GO 3", "JBL GO3", "제이비엘 GO3"],
    mustContain: [["jbl", "제이비엘"], ["go3", "go 3"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 49900,
    released: 2020,
  },
  {
    id: "speaker-jbl-go-4",
    brand: "JBL",
    category: "speaker",
    modelName: "JBL GO 4",
    aliases: ["JBL GO 4", "JBL GO4", "제이비엘 GO4"],
    mustContain: [["jbl", "제이비엘"], ["go4", "go 4"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 59900,
    released: 2024,
  },
  {
    id: "speaker-jbl-flip-6",
    brand: "JBL",
    category: "speaker",
    laneKey: "speaker_jbl_flip6",
    modelName: "JBL Flip 6",
    aliases: ["JBL Flip 6", "JBL Flip6", "JBL 플립6", "제이비엘 플립6"],
    mustContain: [["jbl", "제이비엘"], ["flip6", "flip 6", "플립6"]],
    // Wave 84: Flip 5/7 격리. Flip 5/6/7 모두 USB-C라 단자 구분 불가, 텍스트로만.
    // Flip 7 (2025.2) 출시 후 Flip 6 자연 시세 하락 — 격리 명시 필수.
    mustNotContain: [...SPEAKER_NOISE, "flip 5", "flip5", "플립 5", "플립5", "flip 7", "flip7", "플립 7", "플립7", "flip 4", "플립4", "플립 4", "flip 3"],
    msrpKrw: 149000,
    released: 2021,
  },
  {
    // Wave 16: Bose SoundLink Flex narrow lane.
    // JBL Flip 6 (시세 80k)가 bandFromProfit 1 threshold(20k) 통과 구조적 불가하여
    // 더 wide한 가격 분포 (신품 219k, 중고 시세 100~150k) 를 가진 Bose SoundLink Flex 추가.
    // "soundlink flex" 명시 강제 — SoundLink Mini/Revolve/Color/Micro 변형은 mustNotContain로 제외.
    id: "speaker-bose-soundlink-flex",
    brand: "Bose",
    category: "speaker",
    laneKey: "speaker_bose_soundlink_flex",
    modelName: "Bose SoundLink Flex",
    aliases: ["Bose SoundLink Flex", "보스 사운드링크 플렉스", "bose soundlink flex", "보스 SoundLink Flex"],
    mustContain: [["bose", "보스"], ["soundlink flex", "soundlinkflex", "사운드링크 플렉스", "사운드링크플렉스"]],
    mustNotContain: [...SPEAKER_NOISE, "mini", "revolve", "color", "micro", "soundbar", "사운드바"],
    msrpKrw: 219000,
    released: 2021,
  },
  {
    // Wave 20: Sonos Roam (1st gen, 2021) narrow lane.
    // msrp 269k. 중고 시세 100~200k 추정 → bandFromProfit 1+ 통과 가능.
    // Roam SL/Roam 2/Move/One/Five/Era 등 sub-variant는 mustNotContain로 분리.
    id: "speaker-sonos-roam",
    brand: "Sonos",
    category: "speaker",
    laneKey: "speaker_sonos_roam",
    modelName: "Sonos Roam",
    aliases: ["Sonos Roam", "소노스 롬", "소노스Roam", "소노스 로엄", "소노스 로암"],
    mustContain: [["sonos", "소노스"], ["roam", "롬", "로엄", "로암"]],
    mustNotContain: [
      ...SPEAKER_NOISE,
      // Roam 변형 / 다른 Sonos 라인업 격리
      "roam sl", "roamsl", "roam 2", "roam2",
      "move", "one", "five", "era", "beam", "arc", "play:1", "play:3", "play:5", "sub",
      // 충전 도크/패드만 단독 판매 제외
      "충전도크", "충전 도크", "도크만", "wireless charger", "charging dock",
    ],
    msrpKrw: 269000,
    released: 2021,
  },
  {
    // Wave 20: Marshall Emberton II narrow lane (Sonos Roam은 Bunjang 0건으로 pivot).
    // msrp 219k. 중고 시세 80~150k 추정 → bandFromProfit 1~3 통과 가능.
    // Emberton I/III, Stockwell/Kilburn/Willen/Tufton 등 다른 Marshall portable은 분리.
    id: "speaker-marshall-emberton-ii",
    brand: "Marshall",
    category: "speaker",
    laneKey: "speaker_marshall_emberton_ii",
    modelName: "Marshall Emberton II",
    aliases: ["Marshall Emberton II", "Marshall Emberton 2", "마샬 엠버튼 II", "마샬 엠버튼 2", "마샬엠버튼2"],
    mustContain: [["marshall", "마샬"], ["emberton ii", "emberton 2", "emberton2", "엠버튼 ii", "엠버튼 2", "엠버튼2"]],
    mustNotContain: [
      ...SPEAKER_NOISE,
      // Emberton 다른 세대 격리
      "emberton iii", "emberton 3", "emberton3", "엠버튼 iii", "엠버튼 3", "엠버튼3",
      // 다른 Marshall portable 라인업 분리
      "stockwell", "스탁웰", "kilburn", "킬번", "willen", "윌렌", "tufton", "터프턴", "middleton", "미들턴",
      // 거치/홈 시리즈 분리
      "stanmore", "스탠모어", "acton", "액턴", "woburn", "워번",
      // 헤드폰/이어폰 라인업
      "major", "minor", "monitor ii", "헤드폰", "이어폰",
      // 앰프 (마샬은 기타 앰프 브랜드라 같이 검색됨)
      "기타 앰프", "guitar amp", "콤보앰프",
    ],
    msrpKrw: 219000,
    released: 2022,
  },
  {
    // Wave 20 second pivot: Bose SoundLink Mini II (Marshall Emberton II 150k median 압축으로 pool 미달).
    // msrp 219k (2015 모델). 중고 시세 50~130k → distribution wider → bandFromProfit 1~2 통과 가능.
    // SoundLink Flex/Revolve/Color/Micro 변형은 mustNotContain로 분리.
    id: "speaker-bose-soundlink-mini-ii",
    brand: "Bose",
    category: "speaker",
    laneKey: "speaker_bose_soundlink_mini_ii",
    modelName: "Bose SoundLink Mini II",
    aliases: ["Bose SoundLink Mini II", "보스 사운드링크 미니 II", "Bose SoundLink Mini 2", "보스 사운드링크 미니 2", "사운드링크 미니2"],
    mustContain: [["bose", "보스"], ["soundlink mini ii", "soundlink mini 2", "soundlinkmini2", "사운드링크 미니 ii", "사운드링크 미니 2", "사운드링크미니2", "사운드링크미니 2"]],
    mustNotContain: [
      ...SPEAKER_NOISE,
      // SoundLink 다른 변형 분리
      "flex", "플렉스", "revolve", "color", "micro", "마이크로",
      // Mini I (1세대) 격리 — 미니 II만 lane
      "mini i ", "soundlink mini i ", "사운드링크 미니 i ",
      // 사운드바
      "soundbar", "사운드바",
      // 헤드폰/이어폰
      "qc", "quietcomfort", "qc ultra",
    ],
    msrpKrw: 219000,
    released: 2015,
  },
  {
    id: "speaker-jbl-boombox-2",
    brand: "JBL",
    category: "speaker",
    modelName: "JBL Boombox 2",
    aliases: ["JBL Boombox 2", "JBL 붐박스2", "JBL 붐박스 2"],
    mustContain: [["jbl", "제이비엘"], ["boombox 2", "boombox2", "붐박스2", "붐박스 2"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 599000,
    released: 2020,
  },
  {
    id: "speaker-lg-pk5",
    brand: "LG",
    category: "speaker",
    modelName: "LG PK5",
    aliases: ["LG PK5", "엘지 PK5"],
    mustContain: [["lg", "엘지"], ["pk5", "pk 5"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 199000,
    released: 2018,
  },
  {
    id: "speaker-lg-pk7w",
    brand: "LG",
    category: "speaker",
    modelName: "LG PK7W",
    aliases: ["LG PK7W", "엘지 PK7W", "LG 엑스붐 PK7W"],
    mustContain: [["lg", "엘지"], ["pk7w", "pk 7w"]],
    mustNotContain: [...SPEAKER_NOISE],
    msrpKrw: 299000,
    released: 2018,
  },
  // ─── Desktop narrow-lane Wave 17: Mac mini M2 base 256GB ───
  {
    // Mac mini M2 (2023) 8GB/256GB 정가 990k.
    // 중고 시세 분포 600~850k 추정 → bandFromProfit 1 (20k+) 통과 충분.
    // option-parser는 desktop fallthrough로 [family, model] comparable_key 생성.
    id: "desktop-mac-mini-m2-256",
    brand: "Apple",
    category: "desktop",
    laneKey: "desktop_mac_mini_m2_256",
    modelName: "Apple Mac mini M2 256GB",
    aliases: ["Mac mini M2", "맥미니 M2", "맥미니M2", "Apple Mac mini M2", "Mac mini M2 256"],
    mustContain: [["mac mini", "맥미니", "맥 미니"], ["m2"]],
    // M1/M3/M4/Pro/Ultra/Studio 변형 + 512GB 이상 + 16GB RAM 변형 제외 (base 256/8GB만).
    mustNotContain: ["m1", "m3", "m4", "m2 pro", "m2pro", "m2 ultra", "m2ultra", "mac studio", "맥스튜디오", "imac", "아이맥", "macbook", "맥북", "512gb", "1tb", "2tb", "16gb", "24gb"],
    msrpKrw: 990000,
    released: 2023,
  },
  // ─── Home appliance narrow-lane Wave 19: Dyson V12 Detect Slim ───
  {
    // Dyson V12 Detect Slim (Korea SKU). msrp 약 890k. 중고 시세 350~700k 추정.
    // 다른 V-시리즈(V6/V7/V8/V10/V11/V15/Gen5)와 분리. option-parser는 home_appliance fallthrough로 [family, model] comparable_key 생성.
    id: "home-appliance-dyson-v12-detect-slim",
    brand: "Dyson",
    category: "home_appliance",
    laneKey: "home_appliance_dyson_v12_detect_slim",
    modelName: "Dyson V12 Detect Slim",
    aliases: ["Dyson V12", "다이슨 V12", "다이슨V12", "Dyson V12 Detect Slim", "다이슨 V12 디텍트 슬림"],
    mustContain: [["v12"], ["다이슨", "dyson"]],
    // V12 외 다른 Dyson 모델 + 부품/액세서리/매입/하자 제외.
    mustNotContain: ["v6", "v7", "v8", "v10", "v11", "v15", "gen5", "gen 5", "outsize", "옴니글라이드", "omni-glide", "헤어드라이어", "에어랩", "airwrap", "supersonic", "선풍기", "공기청정기", "히터", "헤드만", "툴만", "배터리만", "필터만", "충전기만", "거치대만", "케이스만", "박스만", "부품용", "파손", "고장", "수리이력", "v12s", "submarine", "서브마린", "물걸레"],
    msrpKrw: 890000,
    released: 2022,
  },
  // ─── Home appliance Wave 21: Roborock S8 Pro Ultra ───
  {
    // Roborock S8 Pro Ultra (flagship robot vacuum + mop, 2023). msrp 1,790k.
    // 중고 시세 600~1,200k 추정 → bandFromProfit 2~3 통과 가능 (distribution wide).
    // Bunjang Roborock 모집단에서 가장 dense (S8 base 0건, Pro Ultra 14건, Qrevo 12건).
    // S8 base/S8+/S8 MaxV/Qrevo/S7/Q-series 등은 mustNotContain로 분리.
    id: "home-appliance-roborock-s8-pro-ultra",
    brand: "Roborock",
    category: "home_appliance",
    laneKey: "home_appliance_roborock_s8_pro_ultra",
    modelName: "Roborock S8 Pro Ultra",
    aliases: ["Roborock S8 Pro Ultra", "로보락 S8 Pro Ultra", "로보락 S8프로울트라", "로보락 S8 프로 울트라", "Roborock S8 ProUltra"],
    mustContain: [["roborock", "로보락"], ["s8 pro ultra", "s8proultra", "s8 프로 울트라", "s8프로울트라", "s8프로 울트라", "s8 프로울트라"]],
    mustNotContain: [
      // S8 다른 변형 분리
      "s8 maxv", "s8maxv", "s8 max v",
      "s8+", "s8 plus", "s8plus",
      // 다른 세대/시리즈
      "s7", "s6", "s5",
      "qrevo", "q revo", "q5", "q7", "q8",
      "g10", "g20", "h7",
      // 부품/소모품/액세서리만
      "걸레만", "솔만", "필터만", "배터리만", "충전기만", "어댑터만", "케이블만",
      "도크만", "충전도크", "거치대만", "케이스만", "박스만",
      "부품용", "파손", "고장", "수리이력", "침수",
      // 매입/구매
      "매입", "삽니다", "구해요", "구매합니다", "구합니다",
      // 타 브랜드 robot vac
      "샤오미", "dreame", "드리미", "ecovacs", "에코백스", "lg 코드제로", "삼성 비스포크",
    ],
    msrpKrw: 1790000,
    released: 2023,
  },
  // ─── Desktop Wave 22: iMac M3 24-inch ───
  {
    // Apple iMac M1 24" (2021). Dense enough in generic "아이맥" query, but
    // must stay separate from older Intel 21/27-inch and newer M3/M4 models.
    id: "desktop-imac-m1-24",
    brand: "Apple",
    category: "desktop",
    laneKey: "desktop_imac_m1_24",
    modelName: "Apple iMac M1 24\"",
    aliases: ["iMac M1", "아이맥 M1", "iMac M1 24", "아이맥 M1 24", "아이맥 24인치 M1"],
    mustContain: [["imac", "아이맥"], ["m1"]],
    mustNotContain: [
      "m2", "m3", "m4", "intel", "인텔",
      "27인치", "27\"", "27in", "21인치", "21.5", "21\"", "21in", "retina 5k", "5k retina",
      "mac studio", "맥 스튜디오", "맥스튜디오", "mac pro", "맥프로", "mac mini", "맥미니", "macbook", "맥북",
      "스탠드만", "어댑터만", "케이블만", "박스만", "케이스만", "부품용", "파손", "고장", "수리이력", "액정파손", "메인보드",
      "매입", "삽니다", "구해요", "구매합니다", "구합니다",
    ],
    msrpKrw: 1690000,
    released: 2021,
  },
  {
    // Apple iMac M3 24" (2023). msrp 1,690~2,090k (8GB/256 base ~ 16GB/512 top).
    // Bunjang probe: M3 67건 (가장 dense), distribution 1.2~1.55M. wide enough for profit_band 1~2.
    // 다른 chip(M1/M2/M4/Intel) + 27"/21" 이전 세대 분리.
    id: "desktop-imac-m3-24",
    brand: "Apple",
    category: "desktop",
    laneKey: "desktop_imac_m3_24",
    modelName: "Apple iMac M3 24\"",
    aliases: ["iMac M3", "아이맥 M3", "iMac M3 24", "아이맥 M3 24", "아이맥 24인치 M3"],
    mustContain: [["imac", "아이맥"], ["m3"]],
    mustNotContain: [
      // 다른 chip 격리
      "m1", "m2", "m4", "intel", "인텔",
      // iMac 27"/21" (Intel 시절) 격리
      "27인치", "27\"", "27in", "21인치", "21.5", "21\"", "21in", "retina 5k", "5k retina",
      // Mac Studio / mini / Pro / MacBook 분리
      "mac studio", "맥스튜디오", "mac pro", "맥프로", "mac mini", "맥미니", "macbook", "맥북",
      // 부품/단품/하자
      "스탠드만", "어댑터만", "케이블만", "박스만", "케이스만", "부품용", "파손", "고장", "수리이력", "액정파손", "메인보드",
      // 매입/구매
      "매입", "삽니다", "구해요", "구매합니다", "구합니다",
    ],
    msrpKrw: 1890000,
    released: 2023,
  },
  {
    // Apple Mac Studio M4 Max 512GB (2025). Query "맥스튜디오" is polluted by
    // MAXSTUDIO apparel; only exact Mac Studio + M4 Max + 512 rows may bind.
    id: "desktop-mac-studio-m4-max-512",
    brand: "Apple",
    category: "desktop",
    laneKey: "desktop_mac_studio_m4_max_512",
    modelName: "Apple Mac Studio M4 Max 512GB",
    aliases: ["Mac Studio M4 Max", "맥 스튜디오 M4 Max", "맥스튜디오 M4 Max", "맥 스튜디오 M4 맥스"],
    mustContain: [["mac studio", "맥 스튜디오", "맥스튜디오"], ["m4 max", "m4max", "m4 맥스"], ["512", "512gb", "512g"]],
    mustNotContain: [
      "m1", "m2", "m3", "m4 pro", "m4pro", "m2 max", "m2max", "m2 ultra", "m2ultra",
      "imac", "아이맥", "mac mini", "맥미니", "macbook", "맥북", "mac pro", "맥프로",
      "1tb", "1테라", "2tb", "2테라", "4tb", "4테라",
      "스탠드만", "어댑터만", "케이블만", "박스만", "케이스만", "부품용", "파손", "고장", "수리이력", "메인보드",
      "매입", "삽니다", "구해요", "구매합니다", "구합니다",
    ],
    msrpKrw: 3290000,
    released: 2025,
  },
  // ─── Camera body-only exact-model internal candidates ───
  {
    id: "camera-canon-eos-r6-mark-ii",
    brand: "Canon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Canon EOS R6 Mark II",
    aliases: ["Canon EOS R6 Mark II", "캐논 EOS R6 Mark II", "알육막투", "R6M2"],
    // Wave 86: body 요구 제거 (R6 Mark II 매물 다수가 "바디" 명시 없음). 대신
    // mustNotContain에 lens kit 패턴 + R6 Mark III/R5/R5 Mark II 격리 강화.
    mustContain: [["eos r6 mark ii", "r6 mark ii", "r6m2", "알육막투"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "r6 mark iii", "r6mark3", "r6m3", "알육막삼", "+ rf ", "+ ef ", "+ 24-", "+ 70-", "+ 28-", "+ 85", "+ 35", "+ 70 200", "+ 24 105", "+ 24 70"],
    msrpKrw: 3199000,
    released: 2022,
  },
  {
    id: "camera-sony-a7m3",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A7 III",
    aliases: ["Sony A7 III", "Sony A7M3", "소니 A7M3", "ILCE-7M3"],
    // Wave 86: body 요구 제거. A7R/A7S/A7C 모든 변형 격리 강화.
    mustContain: [["a7m3", "a7 iii", "a7 3", "ilce 7m3"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a7m2", "a7m4", "a7r3", "a7rm3", "a7r iii", "a7r3", "a7s3", "a7s iii", "a7s ii", "a7sm3", "a7c", "a7c2", "a7c ll", "a7cr", "a7c ii", "ilce-7cm2", "ilce 7cm2", "ilce-7sm2", "ilce 7sm2", "+ rf", "+ ef", "+ 28-75", "+ 24-", "+ 70-", "케이지"],
    msrpKrw: 2499000,
    released: 2018,
  },
  {
    id: "camera-sony-a7c",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A7C",
    aliases: ["Sony A7C", "소니 A7C", "ILCE-7C"],
    // Wave 86: body 요구 제거 + A7C II/A7CR/A7M3/A7S 격리 강화.
    mustContain: [["a7c", "ilce 7c"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a7c2", "a7cr", "a7c ll", "a7c2 ", "a7c ii", "7cm2", "ilce 7cm2", "ilce-7cm2", "a7m3", "a7m4", "a7s2", "a7s3", "ilce 7sm2", "ilce-7sm2", "+ rf", "+ ef", "+ 28-", "+ 24-", "+ 70-", "케이지"],
    msrpKrw: 2199000,
    released: 2020,
  },
  {
    // Wave 87: A7C II (2023.10) — A7C 후속, 33MP, ILCE-7CM2. A7C broad noise 해소.
    id: "camera-sony-a7c-ii",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A7C II",
    aliases: ["Sony A7C II", "소니 A7C II", "Sony A7C2", "소니 A7C2", "A7C ll", "ILCE-7CM2"],
    mustContain: [["a7c2", "a7c ii", "a7c ll", "ilce 7cm2"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a7cr", "ilce 7cr", "a7c rangefinder", "a7m3", "a7m4", "a7s2", "a7s3", "ilce 7sm2", "+ rf", "+ ef", "+ 28-", "+ 24-", "+ 70-", "케이지"],
    msrpKrw: 2999000,
    released: 2023,
  },
  {
    // Wave 87: A7CR (2023.10) — A7C 라인 고해상 61MP variant, ILCE-7CR.
    id: "camera-sony-a7cr",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A7CR",
    aliases: ["Sony A7CR", "소니 A7CR", "ILCE-7CR"],
    mustContain: [["a7cr", "ilce 7cr"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a7c2", "a7c ii", "ilce 7cm2", "a7r", "a7r5", "a7r v", "a7r iv", "a7m3", "a7m4", "+ rf", "+ ef", "+ 28-", "+ 24-", "+ 70-", "케이지"],
    msrpKrw: 4290000,
    released: 2023,
  },
  {
    id: "camera-sony-a5100",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony A5100",
    aliases: ["Sony A5100", "소니 A5100", "ILCE-5100"],
    mustContain: [["a5100", "ilce 5100"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 698000,
    released: 2014,
  },
  {
    id: "camera-canon-eos-m6",
    brand: "Canon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Canon EOS M6",
    aliases: ["Canon EOS M6", "캐논 EOS M6"],
    mustContain: [["eos m6", "캐논 m6"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 899000,
    released: 2017,
  },
  {
    id: "camera-nikon-z9",
    brand: "Nikon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Nikon Z9",
    aliases: ["Nikon Z9", "니콘 Z9"],
    mustContain: [["z9", "니콘 z9"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 6998000,
    released: 2021,
  },
  {
    id: "camera-canon-eos-6d",
    brand: "Canon",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Canon EOS 6D",
    aliases: ["Canon EOS 6D", "캐논 EOS 6D"],
    mustContain: [["eos 6d", "캐논 6d"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 2490000,
    released: 2012,
  },
  {
    id: "camera-fujifilm-x-t4",
    brand: "Fujifilm",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Fujifilm X-T4",
    aliases: ["Fujifilm X-T4", "후지필름 X-T4", "후지 X-T4"],
    mustContain: [["x-t4", "x t4", "xt4"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE],
    msrpKrw: 2099000,
    released: 2020,
  },
  // ─── PlayStation 5 (Standard, Disc/Digital) ─────────
  // narrow lane: ps5_disc_digital_standard (Slim/Pro/PSVR/Switch/액세서리 차단)
  {
    id: "ps5-disc-standard",
    brand: "Sony",
    category: "game_console",
    laneKey: "ps5_disc_digital_standard",
    modelName: "PlayStation 5 (Disc, Standard)",
    aliases: ["PS5 디스크", "PS5 Disc", "플스5 디스크", "플레이스테이션 5 디스크"],
    mustContain: [
      ["ps5", "플스5", "플스 5", "플레이스테이션 5", "playstation 5"],
      ["디스크", "disc"],
    ],
    mustNotContain: [
      "ps5 pro", "ps 5 pro", "플스5 프로", "플스 5 프로", "ps5pro",
      "슬림", "slim", "ps5 slim", "플스5 슬림",
      "디지털 에디션", "digital edition", "디지털에디션",
      "psvr", "psvr2", "ps vr", "vr2", "vr 2",
      "스위치", "switch", "닌텐도", "nintendo",
      "ps4", "ps3", "ps2", "ps1",
      "컨트롤러만", "듀얼센스만", "dualsense만", "충전기만", "케이스만", "스탠드만",
      "기프트", "gift card", "디지털 카드", "월정액",
      "ssd만", "ssd 단품", "카드만",
      "구합니다", "삽니다", "매입", "wts", "wtb",
      "부품용", "고장",
    ],
    msrpKrw: 698000,
    released: 2020,
  },
  {
    id: "ps5-digital-standard",
    brand: "Sony",
    category: "game_console",
    laneKey: "ps5_disc_digital_standard",
    modelName: "PlayStation 5 (Digital, Standard)",
    aliases: ["PS5 디지털", "PS5 Digital", "플스5 디지털", "플레이스테이션 5 디지털 에디션"],
    mustContain: [
      ["ps5", "플스5", "플스 5", "플레이스테이션 5", "playstation 5"],
      ["디지털", "digital"],
    ],
    mustNotContain: [
      "ps5 pro", "ps 5 pro", "플스5 프로", "플스 5 프로", "ps5pro",
      "슬림", "slim", "ps5 slim", "플스5 슬림",
      "디스크 에디션", "disc edition", "디스크에디션",
      "psvr", "psvr2", "ps vr", "vr2", "vr 2",
      "스위치", "switch", "닌텐도", "nintendo",
      "ps4", "ps3", "ps2", "ps1",
      "컨트롤러만", "듀얼센스만", "dualsense만", "충전기만", "케이스만", "스탠드만",
      "기프트", "gift card", "디지털 카드", "월정액", "psn",
      "ssd만", "ssd 단품", "카드만",
      "구합니다", "삽니다", "매입", "wts", "wtb",
      "부품용", "고장",
    ],
    msrpKrw: 568000,
    released: 2020,
  },
  // ─── Nintendo Switch OLED (2021-10) ─────────────────
  // narrow lane: switch_oled (Switch 2/Lite/일반 스위치/PS5/액세서리 차단)
  {
    id: "switch-oled",
    brand: "Nintendo",
    category: "game_console",
    laneKey: "switch_oled",
    modelName: "Nintendo Switch OLED",
    aliases: ["Nintendo Switch OLED", "닌텐도 스위치 OLED", "스위치 올레드", "스위치 OLED"],
    mustContain: [
      ["닌텐도", "nintendo", "스위치", "switch"],
      ["oled", "올레드"],
    ],
    mustNotContain: [
      "스위치 2", "switch 2", "스위치2", "switch2",
      "라이트", "lite",
      "일반 스위치", "스위치 1",
      "ps5", "ps4",
      "컨트롤러만", "조이콘만", "게임만", "게임 팩", "게임 카드",
      "기프트", "gift",
      "충전기만", "케이스만",
      "부품", "고장",
      "매입", "삽니다",
    ],
    msrpKrw: 414000,
    released: 2021,
  },
  // ─── PlayStation 5 Slim (Disc/Digital, 2023-11) ─────
  // narrow lane: ps5_slim (Standard/Pro/PSVR/Switch/액세서리 차단)
  {
    id: "ps5-slim-disc",
    brand: "Sony",
    category: "game_console",
    laneKey: "ps5_slim",
    modelName: "PlayStation 5 Slim (Disc)",
    aliases: ["PS5 슬림 디스크", "PS5 Slim Disc", "플스5 슬림 디스크", "플레이스테이션 5 슬림 디스크"],
    mustContain: [
      ["ps5", "플스5", "플스 5", "플레이스테이션 5"],
      ["슬림", "slim"],
      ["디스크", "disc"],
    ],
    mustNotContain: [
      "ps5 pro", "ps 5 pro", "플스5 프로", "ps5pro",
      "psvr", "psvr2", "vr2", "ps vr",
      "switch", "닌텐도", "nintendo",
      "ps4", "ps3", "ps2", "ps1",
      "컨트롤러만", "듀얼센스만", "dualsense만", "충전기만", "케이스만", "스탠드만",
      "기프트", "gift card", "월정액",
      "ssd만", "ssd 단품",
      "구합니다", "삽니다", "매입",
      "부품용", "고장",
    ],
    msrpKrw: 628000,
    released: 2023,
  },
  {
    id: "ps5-slim-digital",
    brand: "Sony",
    category: "game_console",
    laneKey: "ps5_slim",
    modelName: "PlayStation 5 Slim (Digital)",
    aliases: ["PS5 슬림 디지털", "PS5 Slim Digital", "플스5 슬림 디지털", "플레이스테이션 5 슬림 디지털"],
    mustContain: [
      ["ps5", "플스5", "플스 5", "플레이스테이션 5"],
      ["슬림", "slim"],
      ["디지털", "digital"],
    ],
    mustNotContain: [
      "ps5 pro", "ps 5 pro", "플스5 프로", "ps5pro",
      "psvr", "psvr2", "vr2", "ps vr",
      "switch", "닌텐도", "nintendo",
      "ps4", "ps3", "ps2", "ps1",
      "컨트롤러만", "듀얼센스만", "dualsense만", "충전기만", "케이스만", "스탠드만",
      "기프트", "gift card", "월정액",
      "ssd만", "ssd 단품",
      "구합니다", "삽니다", "매입",
      "부품용", "고장",
    ],
    msrpKrw: 498000,
    released: 2023,
  },
  // ─── AirPods ─────────────────────────────────────────
  {
    id: "airpods-2",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 2nd gen",
    aliases: ["에어팟 2세대", "AirPods 2", "에어팟2"],
    mustContain: [["에어팟", "airpods"], ["2세대", "2 세대", "2nd"]],
    mustNotContain: ["프로", "pro", "max", "맥스", "3세대", "4세대"],
    msrpKrw: 199000,
    released: 2019,
  },
  {
    id: "airpods-3",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 3rd gen",
    aliases: ["에어팟 3세대", "AirPods 3", "에어팟3"],
    mustContain: [["에어팟", "airpods"], ["3세대", "3 세대", "3rd"]],
    mustNotContain: ["프로", "pro", "max", "맥스", "2세대", "4세대"],
    msrpKrw: 269000,
    released: 2021,
  },
  {
    id: "airpods-4",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 4th gen",
    aliases: ["에어팟 4세대", "AirPods 4", "에어팟4"],
    mustContain: [["에어팟", "airpods"], ["4세대", "4 세대", "4th"]],
    // ANC 매물은 airpods-4-anc SKU로만 분류 (별도 제품).
    mustNotContain: ["프로", "pro", "max", "맥스", "2세대", "3세대", "anc", "노이즈 캔슬", "노캔", "노이즈캔슬"],
    msrpKrw: 199000,
    released: 2024,
  },
  {
    id: "airpods-pro-1",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 1st gen",
    aliases: ["에어팟 프로 1세대", "AirPods Pro 1"],
    mustContain: [["에어팟", "airpods"], ["프로", "pro"], ["1세대", "1 세대", "1st"]],
    mustNotContain: ["2세대", "2nd", "max", "맥스", "usb-c", "usbc", "c타입", "타입c"],
    msrpKrw: 329000,
    released: 2019,
  },
  {
    id: "airpods-pro-2-lightning",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 2nd gen (Lightning)",
    aliases: ["에어팟 프로 2세대 라이트닝", "AirPods Pro 2 Lightning"],
    mustContain: [
      ["에어팟", "airpods"],
      ["프로", "pro"],
      ["2세대", "2 세대", "2nd", " 2 ", "프로 2", "프로2"],
    ],
    mustNotContain: ["max", "맥스", "usb-c", "usbc", "c타입", "타입c", "씨타입", "타입씨"],
    msrpKrw: 359000,
    released: 2022,
  },
  {
    id: "airpods-pro-2-usbc",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 2nd gen (USB-C)",
    aliases: ["에어팟 프로 2세대 USB-C", "AirPods Pro 2 USB-C"],
    mustContain: [
      ["에어팟", "airpods"],
      ["프로", "pro"],
      ["2세대", "2 세대", "2nd", "프로 2", "프로2"],
      ["usb-c", "usbc", "c타입", "타입c", "씨타입", "타입씨"],
    ],
    mustNotContain: ["라이트닝", "lightning", "max", "맥스"],
    msrpKrw: 359000,
    released: 2023,
  },
  {
    id: "airpods-4-anc",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods 4 (ANC)",
    aliases: ["에어팟 4세대 ANC", "AirPods 4 ANC", "에어팟4 ANC"],
    // 변형 흡수: "에어팟4 ANC" (공백 없음), "에어팟 4 ANC" 등.
    // 다른 세대는 mustNotContain "1세대/2세대/3세대"로 격리.
    mustContain: [
      ["에어팟", "airpods"],
      ["4세대", "4 세대", "4th", "에어팟4", "에어팟 4", "airpods 4", "airpods4"],
      ["anc", "노이즈 캔슬", "노캔", "노이즈캔슬"],
    ],
    mustNotContain: ["프로", "pro", "max", "1세대", "2세대", "3세대", ...HEADPHONE_NOISE],
    msrpKrw: 249000,
    released: 2024,
  },
  {
    id: "airpods-pro-3",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Pro 3rd gen",
    aliases: ["에어팟 프로 3세대", "AirPods Pro 3", "에어팟프로3"],
    mustContain: [
      ["에어팟", "airpods"],
      ["프로", "pro"],
      ["3세대", "3 세대", "3rd", "프로 3", "프로3"],
    ],
    mustNotContain: [
      "1세대",
      "1st",
      "2세대",
      "2nd",
      "맥스",
      "max",
      "라이트닝",
      "lightning",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 369000,
    released: 2025,
  },
  {
    id: "airpods-max",
    brand: "Apple",
    category: "earphone",
    modelName: "AirPods Max (Lightning)",
    aliases: ["에어팟 맥스", "AirPods Max", "에어팟맥스"],
    mustContain: [["에어팟", "airpods"], ["맥스", "max"]],
    mustNotContain: ["usb-c", "usbc", "c타입", "타입c"],
    msrpKrw: 769000,
    released: 2020,
  },
  {
    id: "airpods-max-usbc",
    brand: "Apple",
    category: "earphone",
    laneKey: "airpods_max_usbc",
    modelName: "AirPods Max (USB-C, 2024)",
    aliases: ["에어팟 맥스 USB-C", "AirPods Max USB-C", "에어팟맥스 USB-C"],
    mustContain: [
      ["에어팟", "airpods"],
      ["맥스", "max"],
      ["usb-c", "usbc", "c타입", "타입c", "씨타입"],
    ],
    mustNotContain: ["라이트닝", "lightning", ...HEADPHONE_NOISE],
    msrpKrw: 769000,
    released: 2024,
  },
  {
    id: "sony-wh-1000xm5",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM5",
    aliases: ["소니 WH-1000XM5", "소니 XM5", "Sony WH-1000XM5"],
    mustContain: [["소니", "sony"], ["wh-1000xm5", "wh1000xm5", "xm5"]],
    mustNotContain: ["xm6", "xm4", "ult900n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 499000,
    released: 2022,
  },
  {
    id: "sony-wh-1000xm4",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM4",
    aliases: ["소니 WH-1000XM4", "소니 XM4", "Sony WH-1000XM4"],
    mustContain: [["소니", "sony"], ["wh-1000xm4", "wh1000xm4", "xm4"]],
    mustNotContain: ["xm6", "xm5", "xm3", "ult900n", "ch720n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 459000,
    released: 2020,
  },
  {
    id: "sony-wh-1000xm3",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM3",
    aliases: ["소니 WH-1000XM3", "소니 XM3", "Sony WH-1000XM3"],
    mustContain: [["소니", "sony"], ["wh-1000xm3", "wh1000xm3", "xm3"]],
    mustNotContain: ["xm6", "xm5", "xm4", "ult900n", "ch720n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 449000,
    released: 2018,
  },
  {
    id: "sony-wh-1000xm6",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-1000XM6",
    aliases: ["소니 WH-1000XM6", "소니 XM6", "Sony WH-1000XM6"],
    mustContain: [["소니", "sony"], ["wh-1000xm6", "wh1000xm6", "xm6"]],
    mustNotContain: ["xm5", "xm4", "ult900n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 599000,
    released: 2025,
  },
  {
    id: "sony-wh-ult900n",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-ULT900N / ULT Wear",
    aliases: ["소니 WH-ULT900N", "소니 ULT WEAR", "Sony ULT Wear"],
    mustContain: [["소니", "sony"], ["wh-ult900n", "wh ult900n", "whult900n", "ult900n", "ult wear", "ultwear"]],
    mustNotContain: ["1000xm", "xm3", "xm4", "xm5", "xm6", "ch720n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 259000,
    released: 2024,
  },
  {
    id: "sony-wh-ch720n",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-CH720N",
    aliases: ["소니 WH-CH720N", "Sony WH-CH720N"],
    mustContain: [["소니", "sony"], ["wh-ch720n", "wh ch720n", "whch720n", "ch720n"]],
    mustNotContain: ["1000xm", "xm3", "xm4", "xm5", "xm6", "ult900n", "ch520", ...HEADPHONE_NOISE],
    msrpKrw: 199000,
    released: 2023,
  },
  {
    id: "sony-wh-ch520",
    brand: "Sony",
    category: "earphone",
    modelName: "Sony WH-CH520",
    aliases: ["소니 WH-CH520", "Sony WH-CH520"],
    mustContain: [["소니", "sony"], ["wh-ch520", "wh ch520", "whch520", "ch520"]],
    mustNotContain: [
      "wh-ch700n",
      "wh ch700n",
      "whch700n",
      "ch700n",
      "wh-ch710n",
      "wh ch710n",
      "whch710n",
      "ch710n",
      "wh-ch500",
      "wh ch500",
      "whch500",
      "ch500",
      "wh-1000xm",
      "xm3",
      "xm4",
      "xm5",
      "xm6",
      "ult900n",
      "ult wear",
      "ultwear",
      "linkbuds",
      "wf-",
      "wf 1000",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 79000,
    released: 2022,
  },
  {
    id: "bose-qc-ultra-headphones",
    brand: "Bose",
    category: "earphone",
    modelName: "Bose QuietComfort Ultra Headphones",
    aliases: ["보스 QC 울트라 헤드폰", "Bose QC Ultra Headphones", "Bose QuietComfort Ultra Headphones"],
    mustContain: [
      ["보스", "bose"],
      ["quietcomfort ultra", "qc ultra", "qc 울트라", "quietcomfort 울트라", "qcultra"],
      ["헤드폰", "headphone", "헤드셋"],
    ],
    mustNotContain: [
      "qc35",
      "qc 35",
      "qc45",
      "qc 45",
      "qc15",
      "qc 15",
      "qc20",
      "qc 20",
      "quietcomfort 35",
      "quietcomfort 45",
      "quietcomfort earbuds",
      "qc 이어버드",
      "qc earbuds",
      "이어버드",
      "earbuds",
      "earphone",
      "soundlink",
      "사운드링크",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 599000,
    released: 2023,
  },
  {
    id: "bose-qc45-headphones",
    brand: "Bose",
    category: "earphone",
    laneKey: "bose_qc45",
    modelName: "Bose QuietComfort 45 Headphones",
    aliases: ["보스 QC45 헤드폰", "Bose QC45 Headphones", "Bose QuietComfort 45 Headphones"],
    mustContain: [
      ["보스", "bose"],
      ["qc 45", "qc45", "quietcomfort 45"],
      ["헤드폰", "headphone", "헤드셋"],
    ],
    mustNotContain: [
      "qc35",
      "qc 35",
      "qc15",
      "qc 15",
      "qc20",
      "qc 20",
      "qc ultra",
      "qc 울트라",
      "quietcomfort 35",
      "quietcomfort 울트라",
      "quietcomfort ultra",
      "quietcomfort earbuds",
      "qc 이어버드",
      "qc earbuds",
      "이어버드",
      "earbuds",
      "earphone",
      "soundlink",
      "사운드링크",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 449000,
    released: 2021,
  },
  {
    id: "beats-studio-pro",
    brand: "Beats",
    category: "earphone",
    modelName: "Beats Studio Pro",
    aliases: ["비츠 스튜디오 프로", "Beats Studio Pro"],
    mustContain: [
      ["비츠", "beats"],
      ["스튜디오 프로", "studio pro", "스튜디오프로", "studiopro"],
    ],
    mustNotContain: [
      "studio 3",
      "studio3",
      "studio 2",
      "studio2",
      "솔로",
      "solo 4",
      "solo4",
      "solo 3",
      "fit",
      "flex",
      "powerbeats",
      "이어버드",
      "earbuds",
      "earphone",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 449000,
    released: 2023,
  },
  {
    id: "bose-qc45",
    brand: "Bose",
    category: "earphone",
    modelName: "Bose QuietComfort 45",
    aliases: ["보스 QC45", "Bose QC45"],
    mustContain: [["보스", "bose"], ["qc45", "qc 45", "quietcomfort 45"]],
    mustNotContain: ["울트라", "ultra", ...HEADPHONE_NOISE],
    msrpKrw: 389000,
    released: 2021,
  },
  {
    id: "beats-solo4",
    brand: "Beats",
    category: "earphone",
    modelName: "Beats Solo 4",
    aliases: ["비츠 솔로 4", "비츠 솔로4", "Beats Solo 4"],
    mustContain: [
      ["비츠", "beats"],
      ["솔로 4", "solo 4", "솔로4", "solo4"],
    ],
    mustNotContain: [
      "솔로 3",
      "solo 3",
      "솔로3",
      "solo3",
      "솔로 2",
      "solo 2",
      "솔로2",
      "solo2",
      "솔로 프로",
      "solo pro",
      "solopro",
      "스튜디오 프로",
      "studio pro",
      "스튜디오프로",
      "studiopro",
      "스튜디오 3",
      "studio 3",
      "studio3",
      "비츠 fit",
      "beats fit",
      "fit pro",
      "비츠 flex",
      "beats flex",
      "파워비츠",
      "powerbeats",
      "이어버드",
      "earbuds",
      "earphone",
      "닥터드레 ep",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 249000,
    released: 2024,
  },
  {
    id: "galaxy-buds-3-pro",
    brand: "Samsung",
    category: "earphone",
    laneKey: "galaxy_buds_3_pro",
    modelName: "Galaxy Buds 3 Pro",
    aliases: ["갤럭시 버즈 3 프로", "갤버즈3프로", "Galaxy Buds 3 Pro", "갤럭시버즈3프로"],
    mustContain: [
      ["갤럭시 버즈", "갤버즈", "galaxy buds"],
      ["3 프로", "3프로", "3 pro"],
    ],
    mustNotContain: [
      "1세대",
      "2세대",
      "버즈 2",
      "버즈2",
      "buds 2",
      "buds2",
      "버즈 1",
      "버즈1",
      "buds 1",
      "buds1",
      "fe",
      "라이브",
      "live",
      "버즈 +",
      "버즈+",
      "buds +",
      "buds+",
      "buds plus",
      ...HEADPHONE_NOISE,
    ],
    msrpKrw: 309000,
    released: 2024,
  },
  {
    id: "sennheiser-accentum",
    brand: "Sennheiser",
    category: "earphone",
    modelName: "Sennheiser Accentum Wireless",
    aliases: ["젠하이저 ACCENTUM", "Sennheiser Accentum"],
    mustContain: [["젠하이저", "sennheiser"], ["accentum", "엑센텀"]],
    mustNotContain: ["hd569", "momentum", ...HEADPHONE_NOISE],
    msrpKrw: 259000,
    released: 2023,
  },
  {
    id: "sennheiser-hd569",
    brand: "Sennheiser",
    category: "earphone",
    modelName: "Sennheiser HD569",
    aliases: ["젠하이저 HD569", "Sennheiser HD569"],
    mustContain: [["젠하이저", "sennheiser"], ["hd569", "hd 569"]],
    mustNotContain: ["accentum", "momentum", ...HEADPHONE_NOISE],
    msrpKrw: 259000,
    released: 2016,
  },

  // ─── Apple Watch ─────────────────────────────────────
  {
    id: "applewatch-se1",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch SE 1st gen",
    aliases: ["애플워치 SE 1세대", "Apple Watch SE 1st gen"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["se"], ["1세대", "1 세대", "1st"]],
    mustNotContain: ["se2", "se 2", "se3", "se 3", "ultra", "series", "시리즈"],
    msrpKrw: 359000,
    released: 2020,
  },
  {
    id: "applewatch-se2",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch SE 2nd gen",
    aliases: ["애플워치 SE 2세대", "애플워치 SE2", "Apple Watch SE 2"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["se2", "se 2", "se 2세대", "se 2nd"]],
    mustNotContain: ["se3", "se 3", "ultra"],
    msrpKrw: 359000,
    released: 2022,
  },
  {
    id: "applewatch-se3",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch SE 3rd gen",
    aliases: ["애플워치 SE3", "애플워치 SE 3세대", "Apple Watch SE 3"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["se3", "se 3", "se 3세대", "se 3rd"]],
    mustNotContain: ["se2", "se 2", "ultra"],
    msrpKrw: 359000,
    released: 2025,
  },
  {
    id: "applewatch-series7",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 7",
    aliases: ["애플워치 7", "애플워치 시리즈 7", "Apple Watch Series 7"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 7", "series 7", " 7 ", "s7", "워치7", "워치 7"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 8", "시리즈 9", "시리즈 10", "series 8", "series 9", "series 10"],
    msrpKrw: 539000,
    released: 2021,
  },
  {
    id: "applewatch-series8",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 8",
    aliases: ["애플워치 8", "애플워치 시리즈 8", "Apple Watch Series 8"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 8", "series 8", " 8 ", "s8", "워치8", "워치 8"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 7", "시리즈 9", "시리즈 10", "series 7", "series 9", "series 10"],
    msrpKrw: 599000,
    released: 2022,
  },
  {
    id: "applewatch-series9",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 9",
    aliases: ["애플워치 9", "애플워치 시리즈 9", "Apple Watch Series 9"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 9", "series 9", " 9 ", "s9", "워치9", "워치 9"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 7", "시리즈 8", "시리즈 10", "series 7", "series 8", "series 10"],
    msrpKrw: 599000,
    released: 2023,
  },
  {
    id: "applewatch-series10",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Series 10",
    aliases: ["애플워치 10", "애플워치 시리즈 10", "Apple Watch Series 10"],
    mustContain: [
      ["애플워치", "apple watch", "applewatch"],
      ["시리즈 10", "series 10", " 10 ", "s10", "워치10", "워치 10"],
    ],
    mustNotContain: ["se", "ultra", "시리즈 7", "시리즈 8", "시리즈 9", "series 7", "series 8", "series 9"],
    msrpKrw: 599000,
    released: 2024,
  },
  {
    id: "applewatch-ultra",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Ultra",
    aliases: ["애플워치 울트라", "Apple Watch Ultra"],
    mustContain: [["애플워치", "apple watch", "applewatch"], ["울트라", "ultra"]],
    mustNotContain: ["울트라 2", "ultra 2", "울트라2", "ultra2"],
    msrpKrw: 1149000,
    released: 2022,
  },
  {
    id: "applewatch-ultra2",
    brand: "Apple",
    category: "smartwatch",
    modelName: "Apple Watch Ultra 2",
    aliases: ["애플워치 울트라 2", "Apple Watch Ultra 2"],
    mustContain: [
      ["애플워치", "applewatch", "apple watch", "에플워치", "워치"],
      ["울트라 2", "ultra 2", "울트라2", "ultra2"],
    ],
    mustNotContain: [
      "울트라 1",
      "ultra 1",
      "울트라1",
      "ultra1",
      "se",
      "series 9",
      "series 10",
      "케이스만",
      "밴드만",
      "스트랩만",
      "충전기만",
      "부품",
      "고장",
      "매입",
      "삽니다",
    ],
    msrpKrw: 1149000,
    released: 2023,
  },

  // ─── Galaxy Watch ─────────────────────────────────────
  {
    id: "galaxywatch-6",
    brand: "Samsung",
    category: "smartwatch",
    modelName: "Galaxy Watch 6",
    aliases: ["갤럭시 워치 6", "갤워치 6", "Galaxy Watch 6"],
    mustContain: [
      ["갤럭시 워치", "갤워치", "galaxy watch", "갤럭시워치"],
      [" 6 ", "워치6", "워치 6"],
    ],
    mustNotContain: [" 7 ", "워치7", "ultra"],
    msrpKrw: 369000,
    released: 2023,
  },
  {
    id: "galaxywatch-7",
    brand: "Samsung",
    category: "smartwatch",
    modelName: "Galaxy Watch 7",
    aliases: ["갤럭시 워치 7", "갤워치 7", "Galaxy Watch 7"],
    mustContain: [
      ["갤럭시 워치", "갤워치", "galaxy watch", "갤럭시워치"],
      [" 7 ", "워치7", "워치 7"],
    ],
    mustNotContain: [" 6 ", "워치6", "ultra"],
    msrpKrw: 339000,
    released: 2024,
  },
  {
    id: "galaxywatch-ultra",
    brand: "Samsung",
    category: "smartwatch",
    modelName: "Galaxy Watch Ultra",
    aliases: ["갤럭시 워치 울트라", "Galaxy Watch Ultra"],
    mustContain: [
      ["갤럭시 워치", "갤워치", "galaxy watch", "갤럭시워치"],
      ["울트라", "ultra"],
    ],
    mustNotContain: [],
    msrpKrw: 829000,
    released: 2024,
  },
  ...CORE_SMARTPHONE_CATALOG,
  ...CORE_TABLET_CATALOG,
  ...CORE_LAPTOP_CATALOG,
  ...CORE_LAPTOP_CATALOG_PRO,
  ...GENERATED_CATALOG_WITH_GATES,
  // Wave 67: 신 사업 카테고리 진입 — 시계 (Casio G-Shock + Seiko 5 Sports), 골프 (Titleist TSR2/TSR3), 카메라 보강 (Sony a6400).
  // Wave 58 §11.D 우선순위 + 11 criteria 통과 후보. internal_only로 진입, 측정 후 ready 승격 결정.
  // §12b 정확성 우선: 모델 코드/명시 토큰만 매칭. 변형 흡수만, silent 추정 X.
  {
    id: "watch-casio-gshock-dw5600",
    brand: "Casio",
    category: "watch",
    laneKey: "watch_gshock_dw5600",
    modelName: "Casio G-Shock DW-5600",
    aliases: ["G-Shock DW-5600", "지샥 DW-5600", "DW5600", "스퀘어 지샥"],
    mustContain: [["dw-5600", "dw5600"]],
    mustNotContain: [...WATCH_NOISE, "ga-2100", "ga2100", "gmw-b5000", "gmwb5000"],
    msrpKrw: 159000,
    released: 1996,
  },
  {
    id: "watch-casio-gshock-ga2100",
    brand: "Casio",
    category: "watch",
    laneKey: "watch_gshock_ga2100",
    modelName: "Casio G-Shock GA-2100 (CasiOak)",
    aliases: ["G-Shock GA-2100", "지샥 GA-2100", "GA2100", "지얄오크", "카시오크"],
    mustContain: [["ga-2100", "ga2100", "지얄오크", "카시오크"]],
    // Wave 84: GA-2200 (2022 후속, 전면 라이트 버튼) / GA-B2100 (솔라+BT) /
    // GM-2100 (스테인리스 베젤) / GMA-S2100 (여성용 미드사이즈) 격리.
    // 디자인 매우 유사한 후속/변형 흡수 risk 차단.
    mustNotContain: [...WATCH_NOISE, "dw-5600", "dw5600", "gmw-b5000", "gmwb5000", "ga-2200", "ga2200", "ga 2200", "ga-b2100", "gab2100", "gm-2100", "gm2100", "gma-s2100", "gma s2100"],
    msrpKrw: 169000,
    released: 2019,
  },
  {
    id: "watch-casio-gshock-gmwb5000",
    brand: "Casio",
    category: "watch",
    laneKey: "watch_gshock_gmwb5000",
    modelName: "Casio G-Shock GMW-B5000 (Full Metal)",
    aliases: ["G-Shock GMW-B5000", "지샥 풀메탈", "GMWB5000", "5000풀메탈"],
    mustContain: [["gmw-b5000", "gmwb5000", "풀메탈 5000", "풀메탈5000"]],
    mustNotContain: [...WATCH_NOISE, "dw-5600", "dw5600", "ga-2100", "ga2100"],
    msrpKrw: 990000,
    released: 2018,
  },
  {
    id: "watch-seiko-5-sports-srpd",
    brand: "Seiko",
    category: "watch",
    laneKey: "watch_seiko_5_sports_srpd",
    modelName: "Seiko 5 Sports SRPD (5KX)",
    aliases: ["Seiko 5 Sports SRPD", "세이코 5 스포츠 SRPD", "SRPD51", "SRPD55", "SRPD61", "SRPD65", "SRPD71", "SRPD79", "SRPD83", "5KX"],
    // Wave 86: mustContain 완화 — "세이코"만 명시되고 "5" 명시 안 한 매물 다수.
    // SRPD prefix는 대부분 Seiko 5 Sports 전용이지만 일부 Presage 변형 (SRPD97/99/07 등) 존재 → mustNotContain 강화.
    mustContain: [
      ["세이코", "seiko"],
      ["srpd", "5kx"],
    ],
    mustNotContain: [...WATCH_NOISE, "sbsa", "프로스펙스", "prospex", "프레사지", "presage", "astron", "스노우플레이크", "snowflake", "드레스워치", "skx", "ssk", "킹세이코", "그랜드세이코", "grand seiko"],
    msrpKrw: 350000,
    released: 2019,
  },
  {
    id: "watch-seiko-5-sports-sbsa",
    brand: "Seiko",
    category: "watch",
    laneKey: "watch_seiko_5_sports_sbsa",
    modelName: "Seiko 5 Sports SBSA",
    aliases: ["Seiko 5 Sports SBSA", "세이코 5 스포츠 SBSA"],
    mustContain: [
      ["seiko 5", "세이코 5", "세이코5"],
      ["sbsa"],
    ],
    mustNotContain: [...WATCH_NOISE, "srpd", "5kx", "프로스펙스", "prospex"],
    msrpKrw: 450000,
    released: 2019,
  },
  {
    id: "sport-golf-titleist-tsr2-driver",
    brand: "Titleist",
    category: "sport_golf",
    laneKey: "sport_golf_titleist_tsr2_driver",
    modelName: "Titleist TSR2 Driver",
    aliases: ["Titleist TSR2 Driver", "타이틀리스트 TSR2 드라이버"],
    mustContain: [
      ["tsr2", "tsr 2"],
      ["드라이버", "driver"],
    ],
    mustNotContain: [...GOLF_DRIVER_NOISE, "tsr3", "tsr 3", "tsr1", "tsi", "ts3", "ts2", "헤드만", "head only"],
    msrpKrw: 950000,
    released: 2022,
  },
  {
    id: "sport-golf-titleist-tsr3-driver",
    brand: "Titleist",
    category: "sport_golf",
    laneKey: "sport_golf_titleist_tsr3_driver",
    modelName: "Titleist TSR3 Driver",
    aliases: ["Titleist TSR3 Driver", "타이틀리스트 TSR3 드라이버"],
    mustContain: [
      ["tsr3", "tsr 3"],
      ["드라이버", "driver"],
    ],
    mustNotContain: [...GOLF_DRIVER_NOISE, "tsr2", "tsr 2", "tsr1", "tsi", "ts3", "ts2", "헤드만", "head only"],
    msrpKrw: 950000,
    released: 2022,
  },
  {
    id: "camera-sony-a6400",
    brand: "Sony",
    category: "camera",
    laneKey: "camera_body_only_exact_model",
    modelName: "Sony Alpha 6400 (a6400)",
    aliases: ["Sony a6400", "소니 a6400", "ILCE-6400", "알파 6400"],
    mustContain: [["a6400", "ilce-6400", "ilce 6400", "알파 6400", "알파6400"], ["바디", "바디만", "body"]],
    mustNotContain: [...CAMERA_BODY_ONLY_NOISE, "a6300", "a6500", "a6600", "a6700"],
    msrpKrw: 1290000,
    released: 2019,
  },
  // Wave 91 (2026-05-15): 일반인 친화 카테고리 확장 — 신발 39 + 가방 34 + 자전거 33 = 106 SKU.
  // 모두 resale ≤200만 (자본 천장 준수). 본품만 정책. 셀러 시세 인식 약한 모델 우선.
  ...SHOE_CATALOG,
  ...BAG_CATALOG,
  ...BIKE_CATALOG,
];

const SKU_MAP = new Map(CATALOG.map((s) => [s.id, s]));
export function skuById(id: string): Sku | undefined {
  return SKU_MAP.get(id);
}

const NORMALIZATIONS: [RegExp, string][] = [
  [/usb[\s\-_]*c/gi, " usbc "],
  [/c[\s\-_]*type/gi, " usbc "],
  [/c\s*타입|타입\s*c|씨\s*타입|타입\s*씨/gi, " usbc "],
  [/1\s*세대|일\s*세대|first|1st/gi, " 1세대 "],
  [/2\s*세대|이\s*세대|second|2nd/gi, " 2세대 "],
  [/3\s*세대|삼\s*세대|third|3rd/gi, " 3세대 "],
  [/4\s*세대|사\s*세대|fourth|4th/gi, " 4세대 "],
  // `(?!\d)` prevents "프로 14" / "프로14" from being consumed as "프로 1" + leftover "4",
  // which previously destroyed any "14"/"15"/etc digit after "프로".
  [/프로\s*2(?!\d)/gi, " 프로 프로2 2세대 "],
  [/프로\s*1(?!\d)/gi, " 프로 프로1 1세대 "],
  [/\bpro\s*2\b/gi, " pro pro2 2세대 "],
  [/\bpro\s*1\b/gi, " pro pro1 1세대 "],
  [/에어팟\s*([234])/g, " 에어팟 $1세대 "],
  [/에어팟프로\s*([123])/g, " 에어팟 프로$1 "],
  [/애어팟/g, " 에어팟 "],
  [/울트라\s*2/gi, " 울트라 2 "],
  [/ultra\s*2/gi, " ultra 2 "],
  [/se\s*([123])/gi, " se$1 "],
  [/시리즈\s*([0-9]+)/g, " 시리즈 $1 "],
  [/series\s*([0-9]+)/gi, " series $1 "],
  [/애플\s*워치/g, " 애플워치 "],
  [/갤럭시\s*워치/g, " 갤럭시워치 "],
  [/아이\s*패드/g, " 아이패드 "],
  [/아이패드\s*(프로|에어|미니)/g, " 아이패드 $1 "],
  [/갤럭시\s*탭/g, " 갤럭시탭 "],
  [/갤\s*탭/g, " 갤탭 "],
  [/air\s*pods/gi, " airpods "],
];

export function normalize(text: string): string {
  let t = (text ?? "").toLowerCase();
  t = t.replace(/\+/g, " plus ");
  for (const [pat, repl] of NORMALIZATIONS) {
    t = t.replace(pat, repl);
  }
  t = t.replace(/[^0-9a-z가-힣]+/g, " ").replace(/\s+/g, " ").trim();
  return ` ${t} `;
}

function tokenHit(normalizedText: string, token: string): boolean {
  const n = normalize(token).trim();
  if (!n) return false;
  if (/^\d+$/.test(n)) return normalizedText.includes(` ${n} `);
  return normalizedText.includes(n);
}

function skuMatches(sku: Sku, normalizedText: string): boolean {
  for (const group of sku.mustContain) {
    if (!group.some((token) => tokenHit(normalizedText, token))) return false;
  }
  for (const token of sku.mustNotContain) {
    if (tokenHit(normalizedText, token)) return false;
  }
  return true;
}

function stripLinkLikeText(text: string): string {
  return String(text ?? "")
    .replace(/https?:\/\/\S+/gi, " ")
    .replace(/\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b/gi, " ");
}

function directSpecificMatch(normalizedText: string): Sku | null {
  const compact = normalizedText.replace(/\s+/g, "");
  if (/(아이폰16e|iphone16e)/i.test(compact) || /iphone\s*16e/i.test(normalizedText)) {
    return skuById("iphone-16e") ?? null;
  }
  if (/(아이패드|ipad).{0,24}a17pro/i.test(compact) || /(아이패드|ipad).{0,32}a17\s*pro/i.test(normalizedText)) {
    return skuById("ipad-mini") ?? null;
  }
  return null;
}

function chooseUniqueCandidate(candidates: Sku[]): Sku | null {
  if (candidates.length === 1) return candidates[0];

  // Narrow lane SKUs are stricter than generated broad family SKUs. If exactly
  // one lane SKU matched alongside broad siblings, prefer the lane instead of
  // dropping the listing as ambiguous. Keep true multi-lane collisions blocked.
  const laneCandidates = candidates.filter(
    (sku) => Boolean(sku.laneKey) && ["laptop", "tablet", "smartphone", "watch", "sport_golf"].includes(sku.category),
  );
  if (laneCandidates.length === 1) return laneCandidates[0];

  return null;
}

function requiresCombinedLaneVeto(sku: Sku | null): sku is Sku {
  return sku !== null && Boolean(sku.laneKey) && ["laptop", "tablet", "smartphone", "watch", "sport_golf"].includes(sku.category);
}

export function ruleMatch(title: string, description = ""): Sku | null {
  const titleNorm = normalize(title);
  const combined = normalize(`${title} ${stripLinkLikeText(description).slice(0, 200)}`);
  const titleDirect = directSpecificMatch(titleNorm);
  if (titleDirect) return requiresCombinedLaneVeto(titleDirect) && !skuMatches(titleDirect, combined) ? null : titleDirect;

  const titleCandidates = CATALOG.filter((s) => skuMatches(s, titleNorm));
  const titleChoice = chooseUniqueCandidate(titleCandidates);
  if (titleChoice) return requiresCombinedLaneVeto(titleChoice) && !skuMatches(titleChoice, combined) ? null : titleChoice;
  if (titleCandidates.length > 1) return null;

  const combinedDirect = directSpecificMatch(combined);
  if (combinedDirect) return combinedDirect;

  const descCandidates = CATALOG.filter((s) => skuMatches(s, combined));
  return chooseUniqueCandidate(descCandidates);
}
