type PhraseReplacement = readonly [pattern: RegExp, value: string];

const PRODUCT_LINE_KOREAN_REPLACEMENTS: PhraseReplacement[] = [
  [/\bLouis\s+Vuitton\b/gi, "루이비통"],
  [/\bBottega\s+Veneta\b/gi, "보테가 베네타"],
  [/\bNew\s+Balance\b/gi, "뉴발란스"],
  [/\bOnitsuka\s+Tiger\b/gi, "오니츠카타이거"],
  [/\bDr\.?\s*Martens\b/gi, "닥터마틴"],
  [/\bThe\s+North\s+Face\b/gi, "노스페이스"],
  [/\bThom\s+Browne\b/gi, "톰브라운"],
  [/\bStone\s+Island\b/gi, "스톤아일랜드"],
  [/\bFear\s+of\s+God\b/gi, "피어오브갓"],
  [/\bComme\s+des\s+Garcons\b/gi, "꼼데가르송"],
  [/\bArc'?teryx\b/gi, "아크테릭스"],
  [/\bAir\s+Force\s*1\b/gi, "에어포스 1"],
  [/\bAir\s+Force\b/gi, "에어포스"],
  [/\bAir\s+Jordan\s*1\b/gi, "에어 조던 1"],
  [/\bAir\s+Jordan\b/gi, "에어 조던"],
  [/\bAir\s+Max\b/gi, "에어맥스"],
  [/\bDunk\s+Low\b/gi, "덩크 로우"],
  [/\bLV\s+Trainer\b/gi, "LV 트레이너"],
  [/\bGalaxy\s+Z\s+Fold\b/gi, "갤럭시 Z 폴드"],
  [/\bGalaxy\s+Z\s+Flip\b/gi, "갤럭시 Z 플립"],
  [/\bGalaxy\s+Tab\b/gi, "갤럭시탭"],
  [/\bMacBook\s+Air\b/gi, "맥북 에어"],
  [/\bMacBook\s+Pro\b/gi, "맥북 프로"],
  [/\biPhone\b/g, "아이폰"],
  [/\biPad\b/g, "아이패드"],
  [/\bAirPods\b/gi, "에어팟"],
  [/\bApple\b/gi, "애플"],
  [/\bSamsung\b/gi, "삼성"],
  [/\bGalaxy\b/gi, "갤럭시"],
  [/\bNike\b/gi, "나이키"],
  [/\bAdidas\b/gi, "아디다스"],
  [/\bAsics\b/gi, "아식스"],
  [/\bSalomon\b/gi, "살로몬"],
  [/\bHoka\b/gi, "호카"],
  [/\bMizuno\b/gi, "미즈노"],
  [/\bVans\b/gi, "반스"],
  [/\bConverse\b/gi, "컨버스"],
  [/\bCrocs\b/gi, "크록스"],
  [/\bPuma\b/gi, "푸마"],
  [/\bYeezy\b/gi, "이지"],
  [/\bPrada\b/gi, "프라다"],
  [/\bGucci\b/gi, "구찌"],
  [/\bChanel\b/gi, "샤넬"],
  [/\bDior\b/gi, "디올"],
  [/\bCeline\b/gi, "셀린느"],
  [/\bHermes\b/gi, "에르메스"],
  [/\bBalenciaga\b/gi, "발렌시아가"],
  [/\bPolo\s+Ralph\s+Lauren\b/gi, "폴로 랄프로렌"],
  [/\bRalph\s+Lauren\b/gi, "랄프로렌"],
  [/\bPolo\b/gi, "폴로"],
  [/\bStussy\b/gi, "스투시"],
  [/\bSupreme\b/gi, "슈프림"],
  [/\bCarhartt\b/gi, "칼하트"],
  [/\bMoncler\b/gi, "몽클레르"],
  [/\bEssentials\b/gi, "에센셜"],
  [/\bBAPE\b/g, "베이프"],
  [/\bCDG\b/g, "꼼데"],
  [/\bJunya\b/gi, "준야"],
  [/\bGazelle\b/gi, "가젤"],
  [/\bSamba\b/gi, "삼바"],
  [/\bSuperstar\b/gi, "슈퍼스타"],
  [/\bCortez\b/gi, "코르테즈"],
  [/\bBlazer\b/gi, "블레이저"],
  [/\bNovablast\b/gi, "노바블라스트"],
  [/\bSuperblast\b/gi, "슈퍼블라스트"],
  [/\bGel\s*Kayano\b/gi, "젤 카야노"],
  [/\bChuck\s*70\b/gi, "척 70"],
  [/\bChuck\s*Taylor\b/gi, "척 테일러"],
  [/\bRun\s*Star\s*Hike\b/gi, "런스타 하이크"],
  [/\bCassette\b/gi, "카세트"],
  [/\bCobble\b/gi, "코블"],
  [/\bGalleria\b/gi, "갤러리아"],
  [/\bMarmont\b/gi, "마몬트"],
  [/\bPocono\b/gi, "포코노"],
  [/\bNylon\b/gi, "나일론"],
  [/\bSaffiano\b/gi, "사피아노"],
  [/\bPadded\b/gi, "패디드"],
  [/\bTech\b/gi, "테크"],
  [/\bMatelasse\b/gi, "마틀라세"],
  [/\bMesh\b/gi, "메쉬"],
  [/\bBandana\b/gi, "반다나"],
  [/\bSide\b/gi, "사이드"],
  [/\bVintage\b/gi, "빈티지"],
  [/\bTrainer\b/gi, "트레이너"],
  [/\bTracksuit\b/gi, "트랙수트"],
  [/\bFirebird\b/gi, "파이어버드"],
  [/\bWindbreaker\b/gi, "바람막이"],
  [/\bFleece\b/gi, "플리스"],
  [/\bAnorak\b/gi, "아노락"],
  [/\bHoodie\b/gi, "후드"],
  [/\bSweatshirt\b/gi, "맨투맨"],
  [/\bCrewneck\b/gi, "크루넥"],
  [/\bPuffer\b/gi, "패딩"],
  [/\bPadding\b/gi, "패딩"],
  [/\bDown\b/gi, "다운"],
  [/\bJacket\b/gi, "자켓"],
  [/\bCoat\b/gi, "코트"],
  [/\bShirt\b/gi, "셔츠"],
  [/\bT-?Shirt\b/gi, "티셔츠"],
  [/\bShort\s+Sleeve\b/gi, "반팔"],
  [/\bLong\s*Sleeve\b/gi, "긴팔"],
  [/\bTee\b/gi, "티셔츠"],
  [/\bKnit\b/gi, "니트"],
  [/\bCardigan\b/gi, "가디건"],
  [/\bPants\b/gi, "팬츠"],
  [/\bCargo\b/gi, "카고"],
  [/\bShorts\b/gi, "반바지"],
  [/\bJogger\b/gi, "조거"],
  [/\bWallet\b/gi, "지갑"],
  [/\bBifold\b/gi, "반지갑"],
  [/\bCard\s+Wallet\b/gi, "카드지갑"],
  [/\bBag\b/gi, "백"],
  [/\bTote\b/gi, "토트"],
  [/\bShoulder\b/gi, "숄더"],
  [/\bBackpack\b/gi, "백팩"],
  [/\bHobo\b/gi, "호보"],
  [/\bCamera\b/gi, "카메라"],
  [/\bBucket\b/gi, "버킷"],
  [/\bMini\b/gi, "미니"],
  [/\bClassic\s+Fit\b/gi, "클래식핏"],
  [/\bPique\b/gi, "피케"],
  [/\b2nd\s+gen\b/gi, "2세대"],
  [/\b3rd\s+gen\b/gi, "3세대"],
  [/\bPro\s+Max\b/g, "프로맥스"],
  [/\bPro\b/g, "프로"],
  [/\bPlus\b/g, "플러스"],
  [/\bMax\b/g, "맥스"],
  [/\bAir\b/g, "에어"],
];

export function localizeProductLineLabel(value: string | null | undefined) {
  let label = String(value ?? "").trim();
  if (!label) return label;

  for (const [pattern, replacement] of PRODUCT_LINE_KOREAN_REPLACEMENTS) {
    label = label.replace(pattern, replacement);
  }

  return label
    .replace(/\s*\/\s*/g, " / ")
    .replace(/\s+/g, " ")
    .trim();
}
