// Daangn region BFS scraper — 인접 region 자동 발견 → 100+ region pool 생성.
//
// 사용법:
//   npx tsx scripts/daangn-region-bfs.ts
//
// 동작:
//   1. seed region (서초4동/사당동/반포동/장안동/이문동 등) 부터 시작
//   2. 각 region 검색 페이지 fetch → "주변 지역" 5개 발견
//   3. BFS depth 3 까지 확장
//   4. 결과 region pool JSON 출력 → 복사해서 daangn.ts 에 박기
//
// 안전:
//   - delay 1000ms (당근 부담 안 줌)
//   - max depth 3 + max total 200
//   - block 감지 즉시 중단

import { fetchDaangnText, parseRobotsTxt, type DaangnRegionSeed } from "../src/lib/daangn";

// Phase 6d: known region seeds (Codex probe) + BFS 통해 인접 확장.
// 알려진 id 가 모두 같은 area (서울 강남/동작/서초/동대문) 라 BFS 가 한 area 갇혔던 문제 fix:
//   1. seed 별로 SEARCH_KEYWORDS 다양화 (나이키, 맥북, 골프채, 가방 등) → 다른 매물 분포 발견 가능
//   2. visited 외 다른 area 의 동 이름 우선 fetch (서울 25구 + 경기 주요시)
const SEED_REGIONS: DaangnRegionSeed[] = [
  { id: "6091", name: "사당동" },
  { id: "6126", name: "반포동" },
  { id: "366", name: "서초4동" },
  { id: "6085", name: "장안동" },
];

// BFS 시 sample search keyword — 다양한 카테고리로 인접 region 다각화.
const SEARCH_KEYWORDS = ["나이키", "맥북", "골프채", "가방", "아이폰", "원피스"];

const MAX_REGIONS = 200;
const MAX_DEPTH = 4;
const DELAY_MS = 700;

// 검색 페이지 HTML 에서 "주변 지역" link 추출
function extractNearbyRegions(html: string): DaangnRegionSeed[] {
  const out: DaangnRegionSeed[] = [];
  // patterns: ?in=동이름-12345 or /kr/region/동이름-12345
  // URL-encoded 한글 + "-" + numeric id
  const re = /[?&]in=([^&"'\s<>]+?)-(\d{1,7})(?:[&"'\s<>]|$)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    const nameRaw = m[1];
    const id = m[2];
    let name: string;
    try {
      name = decodeURIComponent(nameRaw);
    } catch {
      continue;
    }
    if (!name || !/^[가-힣]/.test(name)) continue;  // 한글 시작만
    out.push({ id, name });
  }
  return out;
}

async function bfs() {
  const visited = new Set<string>(SEED_REGIONS.map((r) => r.id));
  const result = new Map<string, DaangnRegionSeed>();
  for (const r of SEED_REGIONS) result.set(r.id, r);

  const queue: Array<{ region: DaangnRegionSeed; depth: number }> = SEED_REGIONS.map((r) => ({
    region: r,
    depth: 0,
  }));

  let kwIdx = 0;
  while (queue.length > 0 && result.size < MAX_REGIONS) {
    const { region, depth } = queue.shift()!;
    if (depth >= MAX_DEPTH) continue;

    // search keyword rotate — 같은 region 도 다른 keyword 로 다른 nearby 보임
    const keyword = SEARCH_KEYWORDS[kwIdx % SEARCH_KEYWORDS.length];
    kwIdx += 1;
    const url = `https://www.daangn.com/kr/buy-sell/?in=${encodeURIComponent(region.name)}-${region.id}&search=${encodeURIComponent(keyword)}`;
    process.stderr.write(`[BFS d=${depth} size=${result.size}] ${region.name}(${region.id}) kw=${keyword}\n`);

    let resp;
    try {
      resp = await fetchDaangnText(url, 12_000);
    } catch (err) {
      process.stderr.write(`  fetch error: ${err instanceof Error ? err.message : err}\n`);
      await new Promise((r) => setTimeout(r, DELAY_MS));
      continue;
    }

    if (resp.blockSignal.blocked) {
      process.stderr.write(`  BLOCK SIGNAL: ${resp.blockSignal.reason} — 중단\n`);
      break;
    }
    if (!resp.ok) {
      process.stderr.write(`  HTTP ${resp.status}\n`);
      await new Promise((r) => setTimeout(r, DELAY_MS));
      continue;
    }

    const nearby = extractNearbyRegions(resp.body);
    let newCount = 0;
    for (const n of nearby) {
      if (visited.has(n.id)) continue;
      visited.add(n.id);
      result.set(n.id, n);
      queue.push({ region: n, depth: depth + 1 });
      newCount += 1;
      if (result.size >= MAX_REGIONS) break;
    }
    process.stderr.write(`  found ${nearby.length} nearby, +${newCount} new (total=${result.size})\n`);

    await new Promise((r) => setTimeout(r, DELAY_MS));
  }

  return [...result.values()];
}

async function main() {
  process.stderr.write(`=== Daangn region BFS — seeds=${SEED_REGIONS.length}, max=${MAX_REGIONS}, depth=${MAX_DEPTH} ===\n\n`);
  const regions = await bfs();
  process.stderr.write(`\n=== DONE — total ${regions.length} regions ===\n\n`);

  // sort by region id numerically for diff-friendly output
  regions.sort((a, b) => Number(a.id) - Number(b.id));

  // TypeScript array literal 출력
  console.log("// === BFS auto-discovered Daangn regions ===");
  console.log("// Generated by scripts/daangn-region-bfs.ts");
  console.log(`// Total: ${regions.length} regions`);
  console.log("export const DEFAULT_DAANGN_REGION_SEEDS: DaangnRegionSeed[] = [");
  for (const r of regions) {
    console.log(`  { id: "${r.id}", name: "${r.name}" },`);
  }
  console.log("];");
}

main().catch((err) => {
  process.stderr.write(`\nfatal: ${err instanceof Error ? err.stack ?? err.message : err}\n`);
  process.exit(1);
});
