// Daangn region brute-force ID scanner.
// BFS 가 같은 area 갇히는 한계 우회 — ID range 직접 scan.
// 무효 ID 시 사당동 fallback 이므로 응답의 dbId 가 요청 ID 와 일치하는 경우만 유효.

import { fetchDaangnText, type DaangnRegionSeed } from "../src/lib/daangn";

const RANGE_START = 1;
const RANGE_END = 9999;
const BATCH_SIZE = 30;     // parallel batch
const DELAY_MS = 50;       // batch 사이 delay
const STEP = 1;            // every ID

function extractMatchingRegion(html: string, expectId: string): DaangnRegionSeed | null {
  // 응답 안 "dbId":"6051","name":"등촌동" 패턴 — id 가 요청 id 와 일치하면 유효 region.
  const re = new RegExp(`"dbId":"${expectId}","name":"([가-힣0-9·\\-]+)"`, "g");
  const m = re.exec(html);
  if (!m) return null;
  return { id: expectId, name: m[1] };
}

async function scanOne(id: number): Promise<DaangnRegionSeed | null> {
  const url = `https://www.daangn.com/kr/buy-sell/?in=t-${id}&search=%EB%82%98%EC%9D%B4%ED%82%A4`;
  try {
    const resp = await fetchDaangnText(url, 8_000);
    if (!resp.ok) return null;
    if (resp.blockSignal.blocked) {
      process.stderr.write(`\n[BLOCK] ${resp.blockSignal.reason}\n`);
      throw new Error("BLOCKED");
    }
    return extractMatchingRegion(resp.body, String(id));
  } catch (err) {
    if ((err as Error).message === "BLOCKED") throw err;
    return null;
  }
}

async function main() {
  const found: DaangnRegionSeed[] = [];
  const total = Math.ceil((RANGE_END - RANGE_START + 1) / STEP);
  let scanned = 0;
  let lastReport = Date.now();

  process.stderr.write(`=== brute scan id=${RANGE_START}..${RANGE_END}, batch=${BATCH_SIZE} ===\n`);

  for (let base = RANGE_START; base <= RANGE_END; base += BATCH_SIZE) {
    const batch: number[] = [];
    for (let i = 0; i < BATCH_SIZE && base + i <= RANGE_END; i += STEP) {
      batch.push(base + i);
    }
    const results = await Promise.all(batch.map((id) => scanOne(id)));
    for (const r of results) {
      if (r) found.push(r);
    }
    scanned += batch.length;
    if (Date.now() - lastReport > 3000) {
      process.stderr.write(`  scanned ${scanned}/${total}, found ${found.length}\n`);
      lastReport = Date.now();
    }
    await new Promise((r) => setTimeout(r, DELAY_MS));
  }

  // dedupe + sort
  const dedup = new Map<string, DaangnRegionSeed>();
  for (const r of found) dedup.set(r.id, r);
  const regions = [...dedup.values()].sort((a, b) => Number(a.id) - Number(b.id));

  process.stderr.write(`\n=== DONE — ${regions.length} valid regions ===\n\n`);

  console.log("// Generated by scripts/daangn-region-brute-scan.ts");
  console.log(`// Range: ${RANGE_START}-${RANGE_END} / Found: ${regions.length}`);
  console.log("export const DEFAULT_DAANGN_REGION_SEEDS: DaangnRegionSeed[] = [");
  for (const r of regions) {
    console.log(`  { id: "${r.id}", name: "${r.name}" },`);
  }
  console.log("];");
}

main().catch((err) => {
  process.stderr.write(`fatal: ${err instanceof Error ? err.stack ?? err.message : err}\n`);
  process.exit(1);
});
